<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
    Espere un momento, por favor...
    <div class="progress">
        <div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <span class="sr-only">100% Completo</span>
        </div>
    </div>
</div>

    <form id="frmPreRegistro" name="frmPreRegistro" class="form-horizontal" method="post" action="/backend/pre-registro/guardar" role="form" enctype="multipart/form-data">    
    <br/>  

    <div class="col-xs-12 form-group"> 
        <label for="nombre" class="col-xs-2 control-label"><span class="naranja">*</span>Nombre:</label>
        <div class="col-xs-4">
            <input type="text" id="nombre" name="nombre" readonly="readonly" class="form-control input-sm required" value="<?php echo $this->registro->nombre ?>"  maxlength="100" placeholder="Nombre" />
        </div>
        <label for="apellido_pat" class="col-xs-2 control-label"><span class="naranja">*</span>Apellido paterno:</label>
        <div class="col-xs-4">
            <input type="text" id="apellido_pat" name="apellido_pat" class="form-control input-sm required" value="<?php echo $this->registro->apellido_pat ?>" readonly="readonly"  maxlength="100" placeholder="Apellido paterno" />
        </div>

    </div>
    <div class="col-xs-12 form-group"> 
        <label for="apellido_mat" class="col-xs-2 control-label"><span class="naranja">*</span>Apellido materno:</label>
        <div class="col-xs-4">
            <input type="text" id="apellido_mat" name="apellido_mat" class="form-control input-sm required" value="<?php echo $this->registro->apellido_mat ?>" readonly="readonly" maxlength="100" placeholder="Nombre" />
        </div>
        <label for="genero" class="col-xs-2 control-label"><span class="naranja">*</span>Genero:</label>
        <div class="col-xs-4">
            <select class="form-control required" name="genero" id="genero" readonly="readonly">
                <option value="1" <?php echo (($this->registro->genero==1)?'selected':'') ?> >Masculino</option>
                <option value="2" <?php echo (($this->registro->genero==2)?'selected':'') ?> >Femenino</option>
            </select>
        </div>
    </div>  
    <div class="col-xs-12 form-group"> 
        <label for="fecha_nacimiento" class="col-xs-2 control-label"><span class="naranja">*</span>Fecha de nacimiento:</label>
        <div class="col-xs-4">
            <input type="text" name="fecha_nacimiento" id="fecha_nacimiento" class="form-control input-sm required" value="<?php echo date_format($this->registro->fecha_nacimiento,'Y-m-d') ?>" readonly="readonly">
        </div>
        <label for="curp" class="col-xs-2 control-label"><span class="naranja"></span>CURP:</label>
        <div class="col-xs-4">
            <input type="text" id="curp" name="curp" class="form-control input-sm " value="<?php echo $this->registro->curp ?>" readonly="readonly" maxlength="20" placeholder="CURP" />
        </div>
    </div>  
    <div class="col-xs-12 form-group"> 
        <label for="rfc" class="col-xs-2 control-label"><span class="naranja"></span>RFC:</label>
        <div class="col-xs-4">
            <input type="text" id="rfc" name="rfc" class="form-control input-sm" value="<?php echo $this->registro->rfc ?>" readonly="readonly" maxlength="20" placeholder="RFC" />
        </div>
        <label for="correo" class="col-xs-2 control-label"><span class="naranja">*</span>Correo electr&oacute;nico:</label>
        <div class="col-xs-4">
            <input type="text" id="correo" name="correo" class="form-control input-sm required" value="<?php echo $this->registro->correo ?>" readonly="readonly" maxlength="100" placeholder="Correo" />
        </div>
    </div>  
    <div class="col-xs-12 form-group"> 
        <label for="telefono" class="col-xs-2 control-label"><span class="naranja">*</span>Tel&eacute;fono:</label>
        <div class="col-xs-4">
            <input type="text" id="telefono" name="telefono" class="form-control input-sm required" value="<?php echo $this->registro->telefono ?>" readonly="readonly" maxlength="20" placeholder="Teléfono" />
        </div>
        <label for="celular" class="col-xs-2 control-label"><span class="naranja"></span>Celular:</label>
        <div class="col-xs-4">
            <input type="text" id="celular" name="celular" class="form-control input-sm" value="<?php echo $this->registro->celular ?>" readonly="readonly" maxlength="100" placeholder="Celular" />
        </div>
    </div>
    <div class="col-xs-12 form-group mb40px">
        <label for="empresa_id" class="col-xs-2 control-label"><span class="naranja">*</span>Empresa:</label>
        <div class="col-xs-4">
            <select class="form-control input-sm required" name="empresa_id" id="empresa_id">
                <option value="" selected>Seleccione una empresa</option>
                <?php foreach ($this->empresas as $empresa): ?>
                    <option value="<?php echo $empresa->id; ?>"><?php echo $empresa->nombre; ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <br>    
    
    <div class="col-xs-12 text-right">
    <input type="hidden" name="id" id="id" value="<?php echo $this->registro->id; ?>" /> <!-- cuando no es nuevo -->
    <button class="btn btn-rojo-1" onclick="guardarPreregistro('frmPreRegistro','frmFiltrosPreRegistro','/backend/pre-registro/grid','/backend/pre-registro/imprimir','/pre-registro/exportar');" type="button" ><i class="fa fa-check-circle"></i> Aceptar</button>
    <button class="btn btn-rojo-1" onclick="cancelar();" type="button" ><i class="fa fa-times-circle"></i> Cancelar</button>
    </div>
    <br/><br/><br/>  

</form>