<div class="panel panel-default" style="margin: 5px 0;">
    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Pre-registros</h3>
        <button type="button" onclick="agregar('/backend/pre-registro/agregar', 0, 'frmPreRegistro','Pre-registro');" class="btn btn-sm btn-default pull-right <?php echo($this->puedeAgregar?"
            ":"hide "); ?>">
            <i class="fa fa-plus"></i>&nbsp;Agregar
        </button>
    </div>
    <div class="panel-body">
        <form name="frmFiltrosPreRegistro" id="frmFiltrosPreRegistro">
            <div class="row margin-bottom-3">

                <div class="col-xs-2">
                    <label for="fnombre" class="sr-only">Nombre</label>
                    <input type="text" name="nombre" id="fnombre" class="form-control input-sm" value="" placeholder="Buscar nombre" />
                </div>
                <div class="col-xs-2">
                    <label for="fpaterno" class="sr-only">Paterno</label>
                    <input type="text" name="paterno" id="fpaterno" class="form-control input-sm" value="" placeholder="Buscar apellido paterno"
                    />
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Materno</label>
                    <input type="text" name="materno" id="fmaterno" class="form-control input-sm" value="" placeholder="Buscar apellido materno"
                    />
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Estados</label>
                    <select name="estado_idS" id="estado_idS" class="form-control input-sm " onchange="cambiaEstado(this);">
                    <option value="">Selecciona un estado</option>
                        <?php foreach ($this->estados as $estado): ?>
                        <?php  echo "<script>console.log( 'estados ids: " . $estado->estadoId . "' );</script>"; ?>
                        <option value="<?php echo $estado->estadoId ?>">
                            <?php echo $estado->estado; ?>
                        </option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Zonas</label>
                    <select name="zona_idS" id="zona_idS" class="form-control input-sm " onchange="cambiaZona(this);">
                    <option value="">Selecciona una zona</option>
                        <!-- <?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
                        <option value="<?php echo $zona->zona_id ?>">
                            <?php echo $zona->znombre; ?>
                        </option>
                        <?php endforeach ?> -->
                    </select>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Tipo</label>
                    <select name="tipo_idS" id="tipo_idS" class="form-control input-sm " onchange="cambiaTipo(this);">
                    <option value="">Selecciona un Tipo</option>
                        <!-- <?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?> -->
                    </select>
                </div>
            </div>
            <div class="row margin-bottom-3">
                <div class="col-xs-4 ">
                    <button class="btn btn-sm btn-default" type="button" onclick="shakeEmpys(); filtrar('frmFiltrosPreRegistro','/backend/pre-registro/grid','/backend/pre-registro/imprimir','/backend/pre-registro/exportar');updateByEstadoZonaTipoNone();">
                        <i class="fa fa-search"></i>&nbsp;Filtrar
                    </button>
                    <button class="btn btn-sm btn-default" type="button" onclick="limpiar('frmFiltrosPreRegistro','/backend/pre-registro/grid');">
                        <i class="fa fa-eraser"></i>&nbsp;Limpiar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="flexigrid"></div>
<div class="height-5"></div>