<div class="panel panel-default" style="margin: 5px 0;">
    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Concentrado de Proyectos</h3>
    </div>
    <div class="panel-body">
        <form name="frmFiltrosCategoria" id="frmFiltrosCategoria">
            <div class="row margin-bottom-3">                
                <div class="col-xs-3">
                    <label for="fnombre" class="sr-only">Nombre</label>
                    <input type="text" name="nombre" id="fnombre" class="form-control input-sm" value="" placeholder="Buscar por empresa"/>
                </div>

                <div class="col-xs-6 text-center">
                    <a onclick="filtrar();" class="btn btn-default btn-sm"><i class="fa fa-search"></i> Filtrar</a>
                    <a onclick="limpiar();" class="btn btn-default btn-sm"><i class="fa fa-eraser"></i> Limpiar</a>
                </div>
    	    </div>
        </form>
    </div>
</div>


<table class="table table-striped cuerpo-concentrado" id="cuerpo_tabla">

</table>

<div class="height-5"></div>
