<div class="container body-content">
<h2>Publicaciones.</h2>
<p>
    
    <hr />
    <b>Título:&nbsp; </b>	El Pacto Mundial de la ONU: lineamientos para el control administrativo en las empresas de la Cámara Mexicana de la Industria de la Construcción.<br />
    <b>Rama:</b>&nbsp;Ciencias Sociales y Administrativas.<br />
    <b>Año:</b>&nbsp;2016<br />
    <b>Registro de Publicación:</b>&nbsp;En proceso (Congreso CICA- Septiembre 2016).<br />
    <b>Autores:</b>&nbsp;López Laguna Ana Bertha.<br />
    
    <hr />
    <b>Título:</b>&nbsp;	Evaluación del desarrollo administrativo en empresas de la zona metropolitana de Guadalajara a través de la asignatura Integradora.<br />
    <b>Rama: </b>&nbsp;	Administración y Finanzas <br />
    <b>Año:</b>&nbsp;	19 de Septiembre del 2015<br />
    <b>Registro de Publicación:</b>&nbsp;	03-2015-093013242500-01<br />
    <b>Autores:</b>&nbsp;	López Laguna Ana Bertha,Macías Brambila Hassem Rubén, Quevedo Salvatierra Ana María,Vázquez Medina Benjamín. <br />

    <hr />
    <b>Título:</b>&nbsp;Versionador de archivos para sistemas de gestión de Calidad <br />
    <b>Rama:</b>&nbsp;Programas de computación <br />
    <b>Año:</b>&nbsp;5 de Octubre del 2015<br />
    <b>Registro de Patente:</b>&nbsp;03-2015-042209590300-01 <br />
    <b>Autores:</b>&nbsp;López Laguna Ana Bertha. Macías Brambila Hassem Ruben. <br />
     
    <hr />
    <b>Título:&nbsp;</b>Base de datos para versionador de archivos para sistemas de gestión de Calidad.<br />
    <b>Rama:</b>&nbsp;Compilación de datos (Base de datos)<br />
    <b>Año:</b>&nbsp;29 de Abril del 2015<br />
    <b>Registro de Patente:</b>&nbsp; 03-2015-042209575700-01<br />
    <b>Autores:</b>&nbsp;Quevedo Salvatierra Ana María. Vázquez Medina Benjamín.<br />
   
    <hr />
    <b>Título:</b>&nbsp;Aplicación web para la gestión versiones en documentos de un Sistema de Gestión de Calidad como herramienta para la certificación en MSQ.<br />
    <b>Rama:</b>&nbsp;Ciencias de Ingeniería y Tecnología.<br />
    <b>Año:</b>&nbsp;	2015<br />
    <b>Registro de Publicación:</b>&nbsp;Congreso Internacional ANIEI<br />
    <b>Autores:&nbsp;</b>Macias Brambila Hassem Ruben,López Laguna Ana Bertha,Quevedo Salvatierra Ana María.<br />
    <hr />
    <b>Título:</b>&nbsp;Las TIC´s como herramienta de apoyo para el proceso de Tutorías en la UTJ.<br />
    <b>Rama:</b>&nbsp;Tutorías<br />
    <b>Año:</b>&nbsp;12 de Junio del 2014<br />
    <b>Registro de Publicación:</b>&nbsp;	ISBN 978-607-95686-2-7<br />
    <b>Autores:</b>&nbsp;López Laguna Ana Bertha.<br />

    <hr />
    <b>Título:</b>&nbsp;Diseño de cuestionario como herramienta de Investigación cuantitativa.<br />
    <b>Rama:</b>&nbsp;Administración y Finanzas<br />
    <b>Año:</b>&nbsp;2014<br />
    <b>Registro de Publicación:&nbsp;</b>Congreso Internacional de Administración.<br />
    <b>Autores:</b>&nbsp;López Laguna Ana Bertha,Macias Brambila Hassem Ruben,Quevedo Salvatierra Ana María.<br />

    <hr />
    <b>Título:</b>&nbsp;Diseño Metodológico para que las MPyMEs obtengan el reconocimiento ESR.<br />
    <b>Rama:</b>&nbsp;Administración y Finanzas <br />
    <b>Año:</b>&nbsp;2013<br />
    <b>Registro de Publicación:</b>&nbsp;ISBN: 978-607-95686-0-3<br />
    <b>Autores:</b>&nbsp;López Laguna Ana Bertha,Macías Brambila Hassem Rubén,Quevedo Salvatierra Ana María,Vázquez Medina Benjamín<br />

    <hr />
    <b>Título:</b>&nbsp;Computación en la Nube <br />
    <b>Rama:</b>&nbsp;Tecnologías de la Información<br />
    <b>Año:</b>&nbsp;2011<br />
    <b>Registro de Publicación:</b>&nbsp;Revista Universo de la Tecnología Año III, Ed. No. 10  Agosto/Noviembre 2011.<br />
    <b>Autores:</b>&nbsp;Zarate Navarro Omar,Espinoza González María de Lourdes,López Laguna Ana Bertha,Quevedo Salvatierra Ana María<br />
    
   
</p>
</div>
