    <div class="container body-content">
        

<h2>Contactanos</h2>
<br />
<div class="table-responsive">
    <table class="table">
        <tr>
            <td width="25%"><img src="/img/ana_lopez.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Ana Bertha López Laguna  </h2>
                    <p><b>PTC Integrante Responsable del CA</b></p>
                    <ul>
                        <li>Maestría en Administración del Factor Humano.</li>
                        <li>Maestría en Gestión de la Calidad (Línea-Barcelona España)</li>
                        <li>Maestría en Metodología de La Enseñanza (Pasante).</li>
                    </ul>
                </div>
<!--                    &nbsp;&nbsp;&nbsp;&nbsp;<b>PTC Integrante Responsable del CA</b><br />
        &nbsp;&nbsp;&nbsp;&nbsp;Maestría en Administración del Factor Humano.<br />
        &nbsp;&nbsp;&nbsp;&nbsp;Maestría en Gestión de la Calidad (Línea-Barcelona España).<br />
        &nbsp;&nbsp;&nbsp;&nbsp;Maestría en Metodología de La Enseñanza (Pasante). <br />
-->                
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:ablopez@utj.edu.mx">ablopez@utj.edu.mx</a>
                </address>
            </td>
        </tr>

        <tr>
            <td width="25%"><img src="/img/hassem.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Hassem Rubén Macías Brambila</h2>
                    <p><b>PTC Integrante</b></p>
                    <ul>
                        <li>Maestría en Metodología de la Investigación Educativa.</li>
                    </ul>
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:hmacias@utj.edu.mx">hmacias@utj.edu.mx</a>
                </address>
                <br />
                <br />
            </td>
        </tr>

        <tr>
            <td width="25%"><img src="/img/ana_quevedo.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Ana María Quevedo Salvatierra    </h2>
                    <p><b>PTC Integrante</b></p>
                    <ul>
                        <li>Maestría en Administración Financiera.</li>
                    </ul>
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:aquevedo@utj.edu.mx">aquevedo@utj.edu.mx</a>
                </address>
                <br />
                <br />
            </td>
        </tr>

        <tr>
            <td width="25%"><img src="/img/benjamin.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Benjamín Vázquez Medina</h2>
                    <p><b>PA Colaborador</b></p>
                    <ul>
                        <li>Especialidad en Comercio y Mercados Internacionales.</li>
                        <li>Especialidad en Metodología de la Investigación Educativa.</li>
                    </ul>
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:benjamin.vazquez@utj.edu.mx">benjamin.vazquez@utj.edu.mx</a>
                </address><br />
            </td>
        </tr>

        <tr>
            <td width="25%"><img src="/img/edgardo.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Edgardo Emmanuel González Del Castillo     </h2>
                    <p><b>PTC Integrante</b></p>
                    <ul>
                        <li>Maestría en Gestión de Tecnologías de la Información y Comunicación.</li>
                    </ul>
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:edelcastillo@utj.edu.mx">edelcastillo@utj.edu.mx</a>
                </address><br />
            </td>
        </tr>

    </table>
</div>
</div>
