    <div class="container body-content">
        

<h2>Cuerpo Acádemico Consolidado</h2>

<br />
<div class="table-responsive">
    <table class="table">
        <tr>
            <td width="25%"><img src="/img/ana_lopez.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Ana Bertha López Laguna  </h2>
                    <p><b>PTC Integrante Responsable del CA</b></p>
                    <ul>
                        <li>Maestría en Administración del Factor Humano.</li>
                        <li>Maestría en Gestión de la Calidad (Línea-Barcelona España)</li>
                        <li>Maestría en Metodología de La Enseñanza (Pasante).</li>
                    </ul>
                </div>
<!--                    &nbsp;&nbsp;&nbsp;&nbsp;<b>PTC Integrante Responsable del CA</b><br />
        &nbsp;&nbsp;&nbsp;&nbsp;Maestría en Administración del Factor Humano.<br />
        &nbsp;&nbsp;&nbsp;&nbsp;Maestría en Gestión de la Calidad (Línea-Barcelona España).<br />
        &nbsp;&nbsp;&nbsp;&nbsp;Maestría en Metodología de La Enseñanza (Pasante). <br />
-->                
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:ablopez@utj.edu.mx">ablopez@utj.edu.mx</a>
                </address>
            </td>
        </tr>

        
        <tr>
            <td width="25%"><img src="/img/ana_quevedo.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Ana María Quevedo Salvatierra    </h2>
                    <p><b>PTC Integrante</b></p>
                    <ul>
                        <li>Maestría en Administración Financiera.</li>
                    </ul>
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:aquevedo@utj.edu.mx">aquevedo@utj.edu.mx</a>
                </address>
                <br />
                <br />
            </td>
        </tr>
 
        <tr>
            <td width="25%">  <img src="/img/adriana.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Adriana Isela Peña Montes de Oca</h2>
                    <p><b>PTC Integrante</b></p>
                   <ul>
                        <li>Doctorado en Planeación Estratégica y Dirección de Tecnología</li>
                    </ul> 
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:adriana.isela@utj.edu.mx">adriana.isela@utj.edu.mx</a>
                </address><br />
            </td>
        </tr>
<tr>
            <td width="25%"><img src="/img/hassem.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Hassem Rubén Macías Brambila</h2>
                    <p><b>PTC Integrante</b></p>
                    <ul>
                        <li>Maestría en Metodología de la Investigación Educativa.</li>
                    </ul>
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:hmacias@utj.edu.mx">hmacias@utj.edu.mx</a>
                </address>
                <br />
                <br />
            </td>
        </tr>

        <tr>
            <td width="25%"><img src="/img/edgardo.jpg" width="200" height="150" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <h2>Edgardo Emmanuel González Del Castillo     </h2>
                    <p><b>PTC Integrante</b></p>
                    <ul>
                        <li>Maestría en Gestión de Tecnologías de la Información y Comunicación.</li>
                    </ul>
                </div>
                <address>
                    <strong>&nbsp;&nbsp;&nbsp;&nbsp;e-mail:</strong>    <a href="mailto:edelcastillo@utj.edu.mx">edelcastillo@utj.edu.mx</a>
                </address><br />
            </td>
        </tr>

    </table>

</div>
<h2>Red de colaboración</h2>
<br />
<div class="table-responsive">
    <table class="table">
     <tr>
            <td width="25%"><img src="/img/utbb.jpg" width="350" height="120" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <ul>
                    <li><p><b>José Cesar Ávila Hernández</b></p></li>
                    <li><p><b>Héctor Salvador García Romo</b></p></li>
                    <li><p><b>Amparo Jazmín Meza Gutiérrez</b></p> </li>
                    </ul>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a  href="http://www.utbb.edu.mx/"> www.utbb.edu.mx/</a>
                    
                      
                </div>
                
            </td>
        </tr>
<tr>
            <td width="25%"><img src="/img/uttt.jpg" width="350" height="120" /><br /></td>
            <td width="75%">
                <div class="col-xs-12">
                    <ul>
                    <li><p><b>Laura Aguilar Maya</b></p></li>
                    <li><p><b>Martha Gabriela García Guerrero</b></p></li>
                    <li><p><b>Víctor Manuel del Villar Delgadillo</b></p> </li>
                    </ul>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a  href="http://www.uttt.edu.mx/"> www.uttt.edu.mx/</a>
                    
                      
                </div>
                
            </td>
        </tr>


     </table>

</div>
</div>
