<div class="container body-content">
	<div class="jumbotron" style="padding-left: 0px !important; padding-right: 0px !important;">
	   <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-width-height: ">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
    <li data-target="#myCarousel" data-slide-to="6"></li>
    <li data-target="#myCarousel" data-slide-to="7"></li>
    <li data-target="#myCarousel" data-slide-to="8"></li>
    <li data-target="#myCarousel" data-slide-to="9"></li>
   
  </ol>

  <!-- Wrapper for slides -->
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/img/ce_expo.jpg" alt="UTJ">
      <div class="carousel-caption">
        <!-- <h3 style="text-shadow: black;">¡Bienvenido!</h3> -->
      </div>
    </div>

    <div class="item">
      <img src="/img/ce_alumnos.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>
    

    <div class="item">
      <img src="/img/ce_rector.jpg" alt="Cuerpo académico.">
      <div class="carousel-caption">
       <!-- <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

    <div class="item">
      <img src="/img/ce_panel.jpg" alt="Cuerpo académico.">
      <div class="carousel-caption">
       <!-- <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

    <div class="item">
      <img src="/img/ce_publico.jpg" alt="UTJ">
      <div class="carousel-caption">
        <!-- <h3 style="text-shadow: black;">¡Bienvenido!</h3> -->
      </div>
    </div>

     <div class="item">
      <img src="/img/ce_entrada.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>
   
     <div class="item">
      <img src="/img/ce_biblioteca.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

     <div class="item">
      <img src="/img/ce_edificio.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

     <div class="item">
      <img src="/img/ce_sombrillas.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

     <div class="item">
      <img src="/img/ce_estacionamiento.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
	    <h2> Responsabilidad Social, Sustentabilidad <br> y Desarrollo Integral para PyMES</h2>

      <h3> Los 10 Principios del Pacto Mundial derivan de declaraciones de Naciones Unidas en materia de derechos humanos, trabajo, medio ambiente y anticorrupción y gozan de consenso universal. </h3>
      <br>
	    <a href="http://www.utj.edu.mx" class="btn btn-primary btn-lg">Universidad Tecnológica de Jalisco &raquo;</a>       
	</div>

	<div class="row">
	    <div class="col-md-4">
	        <h2>Integrantes del Cuerpo Acad&eacute;mico</h2>
	        <br />
	        <p>
	            Ana Bertha López Laguna<br />            
	            Ruben Hassem Macias Brambila<br />
	            Ana Maria Quevedo Salvatierra<br />
	            Benjamin Vázquez Medina<br />
	            Edgardo Emmanuel González del Castillo
	            </p>
		</div>

		<div class="col-md-4">
		    <h2>Proyectos</h2>
		    <p>1.- Sinergia Academia Empresa My PYMEs de México.</p>
		    <p>2.- Responsabilidad Social.</p>
		    <p>
		        <a class="btn btn-default" href="http://www.pactomundial.org/">Pacto Mundial &raquo;</a> 
		    </p>
		     <p>
		        <a class="btn btn-default" href="http://www.cmicjalisco.org/">CMIC Jalisco &raquo;</a> 
		    </p>
		</div>

		<div class="col-md-4">   
		        <h1>Líneas de generación y aplicación del conocimiento:</h1>
		        <p>1.- Responsabilidad Social y Sustentabilidad. <br />
		           2.- Proyectos Industriales, Administración Estratégica y Marketing. <br />
		           3.- Gestión, Calidad Total y Finanzas empresariales. <br />
		           4.- Tecnologías de la Información y Comunicación para PyMES.</p>
		</div>	    
	</div>

</div>

