<div class="container body-content">
	<div class="jumbotron" style="padding-left: 0px !important; padding-right: 0px !important;">
	   <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-width-height: ">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
    <li data-target="#myCarousel" data-slide-to="6"></li>
    <li data-target="#myCarousel" data-slide-to="7"></li>
    <li data-target="#myCarousel" data-slide-to="8"></li>
    <li data-target="#myCarousel" data-slide-to="9"></li>
    <li data-target="#myCarousel" data-slide-to="10"></li>
    <li data-target="#myCarousel" data-slide-to="11"></li>
    <li data-target="#myCarousel" data-slide-to="12"></li>
   
  </ol>

  <!-- Wrapper for slides -->
  <!-- Wrapper for slides -->



  <div class="carousel-inner" role="listbox">

     <div class="item active">
      <img src="/img/minerva.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>

    </div>  
     <div class="item">
      <img src="/img/cmic2018.jpg" alt="">
      <div class="carousel-caption">
      
      </div>
    </div>






 <div class="item">
    <img src="/img/ca02.jpg" alt="">
     
      <div class="carousel-caption">
        <!-- <h3 style="text-shadow: black;">¡Bienvenido!</h3> -->
      </div>
    </div>



    <div class="item">
    <img src="/img/camara.jpg" alt="">
     
      <div class="carousel-caption">
        <!-- <h3 style="text-shadow: black;">¡Bienvenido!</h3> -->
      </div>
    </div>
    <div class="item">
    <img src="/img/gdl.jpg" alt="">
     
      <div class="carousel-caption">
        <!-- <h3 style="text-shadow: black;">¡Bienvenido!</h3> -->
      </div>
    </div>
 <div class="item">
       <img src="/img/ce_alumnos.jpg" alt="UTJ">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>





     <div class="item">
    <img src="/img/matute.jpg" alt="">
     
      <div class="carousel-caption">
        <!-- <h3 style="text-shadow: black;">¡Bienvenido!</h3> -->
      </div>
    </div>

  <div class="item">
      <img src="/img/ce_rector.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>


     

  <div class="item">
      <img src="/img/cierrecmic2017.jpg" alt="UTJ">
      <div class="carousel-caption">
        <!-- <h3 style="text-shadow: black;">¡Bienvenido!</h3> -->
      </div>
    </div>

  
   

    <div class="item">
      <img src="/img/bahia.jpg" alt="Cuerpo académico.">
      <div class="carousel-caption">
       <!-- <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

    <div class="item">
      <img src="/img/red.jpg" alt="Cuerpo académico.">
      <div class="carousel-caption">
       <!-- <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

       <div class="item">
      <img src="/img/UTBB.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

 <div class="item">
      <img src="/img/ce_entrada.jpg" alt="">
      <div class="carousel-caption">
      <!--  <h3>Constru Expo 2017</h3> -->
      </div>
    </div>

    

  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
	    <h2> <b>Responsabilidad Social, Sustentabilidad <br> y Desarrollo Integral para PyMES</b></h2>
      <br>   
      <a href="http://www.utj.edu.mx" class="btn btn-primary btn-lg">Universidad Tecnológica de Jalisco &raquo;</a>     
       <br><br>
 <h3><b>Universidad Incluyente (UI)</b></h3>
 <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;El principio y el centro de la universidad no es el conocimiento.
Es la humanidad en su diversidad dialogante y el ser humano en su comprensión e inscripción en los procesos de la vida. 

     <br> <br>
    Las 5 dimensiones de la responsabilidad Social Universitaria son:
     <br> <br>
      <ul>

<li type="disc">Medio ambiente</li>

<li type="disc">Social</li>

<li type="disc">Organizacional</li>
<li type="disc">Del conocimiento</li>
<li type="disc">Educación</li>

</ul>

</h4>
      <h3><b>Distintivo Empresa Familiarmente Responsable (DEFR)</b></h3>
      <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Es un instrumento desarrollado por la Secretaria del Trabajo y Previsión Social (STPS) que tiene como objetivo el reconocimiento de aquellos centros de trabajo que implementan y promueven en su interior políticas y prácticas para que las personas trabajadoras se desarrollen de una manera integral: en el trabajo, en su ámbito personal, familiar y en lo profesional. 
     <br> <br>
     La evaluación de dichas prácticas está integrada por los siguientes ejes:
     <br> <br>
      <ul>

<li type="disc">Conciliación trabajo – familia</li>

<li type="disc">Igualdad de oportunidades</li>

<li type="disc">Prevención de la violencia laboral y del hostigamiento sexual</li>

</ul>

</h4>

  <h3><b>Empresas Socialmente Responsables (ESR)</b></h3>  
    <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  El Distintivo ESR ® es un reconocimiento otorgado anualmente en México por el Centro Mexicano para la Filantropía (CEMEFI).
 
Dicho distintivo no sólo agrega valor a la marca y rentabilidad, sino que acredita a las empresas ante sus empleados, inversionistas, clientes, autoridades y sociedad en general, como una organización comprometida voluntaria y públicamente con una gestión socialmente responsable como parte de su cultura y estrategia de negocio.
</h4>
<h3><b>Capital Intelectual (CI)</b></h3>

<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Plantea que el valor de mercado de una compañia  viene determinado por un capital financiero y unos valores ocultos que, en su conjunto, denominan capital intelectual. Donde se propone la manera de  medirlo, teniendo en cuenta que cualquier valoración que se haga no solo debe contener indicadores pertinentes sino también presentar esas medidas en una forma que sea fácilmente inteligible, aplicable y comparable con otras empresas.  Ademas debe ser un instrumento de navegación que lleve en su conjunto a producir un significado comprensible de la capacidad futura y sostenible de producir beneficios. Se encuentra formado por: 
<br><br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Capital Humano: Que recoge todas las capacidades individuales, los conocimientos, las destrezas y la experiencia de los empleados y directivos de la empresa. Ademas incluye la creatividad e inventiva de la organización.<br> <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Capital Estructural: Se describe como la infraestructura que incorpora, forma y sostiene el capital humano. Es tambien la capacidad organizacional que incluye los sistemas físicos usados para transmitir y almacenar el material intelectual. Formado por activos de infraestructura y de propiedad industrial.<br> Por tanto, recoge diversos componentes que pueden agruparse en:
<br>

 <ul>

<li type="disc">Capital organizacional: La inversión  de la empresa en sistemas, herramientas y filosofia operativa acelera la corriente de conocimientos a través de la organización y hacia fuera mediante los canales de abastecimiento y distribución.</li>

<li type="disc"> Capital innovación: La capacidad de renovación y los resultados de la innovación en forma de derechos comerciales protegidos, propiedad intelectual y otros activos intangibles y talentos usados para crear y llevar rápidamente al mercado nuevos productos y servicios. </li>

<li type="disc"> Capital proceso: Los procesos de trabajo, técnicas y programas para empleados que aumentan y fortalecen la eficiencia de la producción o la prestación de servicios. </li>
<li type="disc"> Capital clientela: Recoge las relaciones con los clientes y su lealtad. </li>
</ul>


	</div>

	<div class="row">
	    <div class="col-md-4">
	        <h2>Integrantes del Cuerpo Acad&eacute;mico</h2>
	        <br />
	        <p>
	            Ana Bertha López Laguna<br />            	            
	            Ana Maria Quevedo Salvatierra<br />	
              Adriana Isela Peña Montes de Oca<br />
              Ruben Hassem Macias Brambila<br />             
	            Edgardo Emmanuel González del Castillo
	            </p>
		</div>

		<div class="col-md-4">
		    <h2>Proyectos</h2>
		    <p>1.- Sinergia Academia Empresa My PYMEs de México.</p>
		    <p>2.- Responsabilidad Social.</p>
		    <p>
		        <a class="btn btn-default" href="http://www.pactomundial.org.mx/site/">Pacto Mundial &raquo;</a> 
		    </p>
		     <p>
		        <a class="btn btn-default" href="http://www.cmicjalisco.org/">CMIC Jalisco &raquo;</a> 
		    </p>
		</div>

		<div class="col-md-4">   
		        <h1>Líneas de generación y aplicación del conocimiento:</h1>
		        <p>1.- Responsabilidad Social y Sustentabilidad. <br />
		           2.- Proyectos Industriales, Administración Estratégica y Marketing. <br />
		           3.- Gestión, Calidad Total y Finanzas empresariales. <br />
		           4.- Tecnologías de la Información y Comunicación para PyMES.</p>
		</div>	    
	</div>

</div>

