	<div class="panel-body">
	    <br/>
	    <div class="col-md-12">
	    <h3 class="text-center"><?php echo $this->encuesta->nombre ?></h3>
	          	
	      <!-- tabs left -->
		        
	         <div class="col-xs-12 cuerpo-encuesta">
		         <?php $preguntas = Preguntas::obtienePreguntasEncuesta($this->encuesta->id); ?>
		         <?php foreach ($preguntas as $pregunta): ?>
		         	<div class="col-xs-6 form-group">
			         		<div class="col-xs-12">
				         		<label class="ajuste-etiqueta control-label"><?php echo $pregunta->descripcion; ?></label>
			         		</div>
										         		
							<div class="col-xs-12">
		         			<?php $respuesta = Respuesta::obtieneRespuesta($this->persona_seleccionada, $pregunta->id, $this->encuesta->zona_id, $this->encuesta->tipo_id); ?>
		         			<?php if ($pregunta->tipo == 1): //pregunta corta ?>
		         				<p class="text-justify">R: <?php echo $respuesta->descripcion; ?></p>
		         			<?php endif ?>
		         			<?php if ($pregunta->tipo == 2): //pregunta larga ?>
		         				<p class="text-justify">R: <?php echo $respuesta->descripcion; ?></p>
		         			<?php endif ?>
		         			<?php if ($pregunta->tipo == 3): ?>
			         				<p class="text-justify">R: <?php echo $respuesta->descripcion; ?></p>
		         			<?php endif ?>
		         			<?php if ($pregunta->tipo == 4): ?>
		         				<?php 
		         				$respuestas_usuario = '';
		         				$opciones = My_Comun::obtenerFiltroSQL('opciones_pregunta',' WHERE status=1 AND pregunta_id='.$pregunta->id,' opcion ASC '); 
		         				?>
		         				<?php foreach ($opciones as $opcion): ?>
				         			<?php $respuesta2 = Respuesta::obtieneRespuestaEspecial($opcion->opcion, $pregunta->id, $this->encuesta->zona_id, $this->encuesta->tipo_id); ?>
		         					<?php if ($respuesta2->id!= ''){
		         						$respuestas_usuario .= $opcion->opcion.', ';
		         					 } ?>
		         				<?php endforeach ?>
		         				<?php $respuestas_usuario = substr($respuestas_usuario, 0, -2); ?>
			         				<p class="text-justify">R: <?php echo $respuestas_usuario; ?></p>
		         			<?php endif ?>
		         		</div>
		         	</div>
		         <?php endforeach ?>
	         </div>
	    </div>
	    <br>
	</div>