<div class="panel panel-default" style="margin: 5px 0;">
    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Concentrado</h3>
    </div>
    <div class="panel-body">
        <form name="frmFiltrosCategoria" id="frmFiltrosCategoria">
            <div class="row margin-bottom-3">
                <div class="col-xs-3">
                    <label for="nombre" class="sr-only">Nombre</label>
                    <input type="text" name="nombre" id="nombre" class="form-control input-sm" value="" placeholder="Buscar por nombre" />
                </div>
                <div class="col-xs-2">
                    <label for="estado_id" class="sr-only">Estados</label>
                    <select name="estado_id" id="estado_id" class="form-control input-sm " onchange="cambiaEstado(this);">
                    <option value="">-Selecciona un estado-</option>
                        <?php foreach ($this->estados as $estado): ?>
                        <?php  echo "<script>console.log( 'estados ids: " . $estado->estadoId . "' );</script>"; ?>
			    			<option value="<?php echo $estado->estadoId ?>"><?php echo $estado->estado; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                <div class="col-xs-2">
                    <label for="zona_id" class="sr-only">Zonas</label>
                    <select name="zona_id" id="zona_id" class="form-control input-sm required" onchange="cambiaZona(this);">
                    <option value="">-Selecciona una zona-</option>
			    		<?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                <div class="col-xs-2">
                    <label for="tipo_id" class="sr-only">Tipo</label>
                    <select name="tipo_id" id="tipo_id" class="form-control input-sm required" onchange="cambiaTipo(this);">
                    <option value="">-Selecciona un Tipo-</option>
			    		<?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                <div class="col-xs-2">
                    <label for="categoria_id" class="sr-only">Categoria</label>
                    <select name="categoria_id" id="categoria_id" class="form-control input-sm required" onchange="">
                    <option value="">-Selecciona una categoria-</option>
			    		<?php foreach ($this->categorias as $categoria): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $categoria->id . "' );</script>"; ?>
			    			<option value="<?php echo $categoria->id ?>"><?php echo $categoria->nombre; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                <!-- <div class="col-xs-3">
                    <label for="Zid" class="sr-only">Zonas</label>
                    <select id="Zid" name="zona" onChange=cargaTablaZona() class="form-control input-sm">
                        <option value="">- Selecciona zona -</option>
                        <?php foreach ($this->zonasName as $zname): ?>
                        <option value="<?php echo $zname->id; ?>">
                            <?php echo $zname->zona_nombre ?>
                        </option>
                        <?php endforeach ?>
                    </select>
                </div> -->

                <!-- <div class="col-xs-3">
                    <label for="encuestaCat" class="sr-only">Categoria</label>
                    <select id="encuestaCat" name="encuestaCat" onChange="" class="form-control input-sm">
                        <option value="">- Selecciona Encuesta -</option>
                        <?php foreach ($this->encu as $zname): ?>
                        <?php $cate = My_Comun::obtenerFiltroSQL('categoria', 'where status = 1 and id = '.$zname->categoria_id, 'nombre asc'); ?>
                        <option value="<?php echo $zname->id; ?>">
                        <?php echo $zname->nombre ?>
                        <?php foreach ($cate as $hh): ?>
                        <?php if ($hh->nombre != ''){
                            echo ' - '.$hh->nombre;
                        } ?>

                            <?php endforeach ?>
                        </option>
                        <?php endforeach ?>
                    </select>
                </div> -->

                <!-- <div class="col-xs-3 text-center">
                    <a onclick="filtrar();" class="btn btn-default btn-sm">
                        <i class="fa fa-search"></i> Filtrar</a>
                    <a onclick="limpiar();" class="btn btn-default btn-sm">
                        <i class="fa fa-eraser"></i> Limpiar</a>

                </div> -->
            </div>
            <div class="row margin-bottom-2">
            <div class="col-xs-3 text-left">
                    <a onclick="filtrar();" class="btn btn-default btn-sm">
                        <i class="fa fa-search"></i> Filtrar</a>
                    <a onclick="limpiar();" class="btn btn-default btn-sm">
                        <i class="fa fa-eraser"></i> Limpiar</a>

                </div>

                </div>
        </form>
    </div>
</div>



<table class="table table-striped cuerpo-concentrado" id="cuerpo_tabla">

</table>

<div class="height-5"></div>