<div class="panel panel-default" style="margin: 5px 0;">
    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Concentrado</h3>
    </div>
    <div class="panel-body">
        <form name="frmFiltrosCategoria" id="frmFiltrosCategoria">
            <div class="row margin-bottom-3">                
                <div class="col-xs-3">
                    <label for="fnombre" class="sr-only">Nombre</label>
                    <input type="text" name="nombre" id="fnombre" class="form-control input-sm" value="" placeholder="Buscar por nombre"/>
                </div>
                <div class="col-xs-3">
                <label for="fstatus" class="sr-only">Categor&iacute;a</label>
                    <select id="fcategoria" name="categoria" class="form-control input-sm">
                        <option value="">- Todas las categor&iacute;as -</option>
                        <?php foreach ($this->categorias as $categoria): ?>
                            <option value="<?php echo $categoria->id; ?>"><?php echo $categoria->nombre ?></option>
                            
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="col-xs-6 text-center">
                    <a onclick="filtrar();" class="btn btn-default btn-sm"><i class="fa fa-search"></i> Filtrar</a>
                    <a onclick="limpiar();" class="btn btn-default btn-sm"><i class="fa fa-eraser"></i> Limpiar</a>
                    
                </div>
    	    </div>
        </form>
    </div>
</div>

<table class="table table-striped cuerpo-concentrado" id="cuerpo_tabla">

</table>

<div class="height-5"></div>
