<thead>
    <tr class="">
        <th class="text-center ancho-celda" style="text-align: left;">Empresa</th>
        <th class="text-center ancho-celda" style="text-align: left;">Nombre</th>
        <?php  $filtro_zona .= " and zona_id = ".$zona->id." "; ?>
        <?php foreach ($this->encuestas as $encuesta): ?>
            <th class="text-center ancho-celda"><?php echo $encuesta->nombre; ?></th>
        <?php endforeach ?>
        <th class="text-center">Exportar</th>
    </tr>
</thead>
<tbody>
    <?php foreach ($this->personas as $persona): ?>
        <tr>
        <?php $contador = 0; ?>
            <td ><?php echo $persona->empresa; ?></td>
            <td><?php echo $persona->nombre.' '.$persona->apellido_pat.' '.$persona->apellido_mat?></td>
            <?php foreach ($this->encuestas as $encuesta): ?>
                <td class="text-center ancho-celda">
                    <?php if (Encuesta::verificaEncuesta($persona->id, $encuesta->id) == 1): ?>
                        <?php $contador = 1; ?>
                        <a class="cursor-modificado" onclick="muestraEncuesta(<?php echo $persona->id ?>,<?php echo $encuesta->id; ?>);">
                            <i class="fa fa-check fa-lg"></i>
                        </a>
                    <?php endif ?>
                </td>
            <?php endforeach ?>
            <td class="text-center">
                <?php if ($contador == 1): ?>
                    <a class="btn btn-sm btn-default" target="_blank" href="/backend/concentrado/exportar/persona/<?php echo $persona->id ?>">
                        <i class="fa fa-file-excel-o fa-lg"></i>&nbsp;Exportar
                    </a>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
</tbody>
