<div class="container">
	<div class="panel-body">
	    <br/>  
	    <div class="col-md-12">
	    <h3>Encuestas</h3>
	          	
	      <!-- tabs left -->
	      <div class="tabbable tabs-left">
	        <ul class="nav nav-tabs">
	        	<?php $contador = 0; ?>
			<?php foreach ($this->encuestas as $encuesta){ ?>

		        <li class="<?php echo (($contador == $this->num_encuesta)?'active':''); ?>"><a href="#_<?php echo $encuesta->id; ?>" data-toggle="tab"><?php echo $encuesta->nombre; ?></a></li>
		        <?php $contador++; ?>
			<?php } ?>
<!--	          <li><a href="#a" data-toggle="tab">One</a></li>
	          <li class="active"><a href="#b" data-toggle="tab">Two</a></li>
	          <li><a href="#c" data-toggle="tab">Twee</a></li>
-->	        </ul>
	        <div class="tab-content">
	        <?php $contador2 = 0; ?>
	        <?php foreach ($this->encuestas as $encuesta): ?>
		         <div class="tab-pane <?php echo (($contador2 == $this->num_encuesta)?'active':''); ?>" id="_<?php echo $encuesta->id; ?>">
			         <div class="col-xs-10 cuerpo-encuesta">
			         	<h3 class="col-xs-12 text-center"><?php echo $encuesta->nombre; ?></h3>
			         <?php $preguntas = Preguntas::obtienePreguntasEncuesta($encuesta->id); ?>
			         <?php foreach ($preguntas as $pregunta): ?>
			         	<div class="col-xs-6 form-group">
			         		<label class="col-xs-12"><?php echo $pregunta->descripcion; ?></label>
			         		<div class="col-xs-12">
			         			<?php $respuesta = Respuesta::obtieneRespuesta(Zend_Auth::getInstance()->getIdentity()->persona_id, $pregunta->id); ?>
			         			<?php if ($pregunta->tipo == 1): //pregunta corta ?>
			         				<p class="text-justify">R: <?php echo $respuesta->descripcion; ?></p>
			         			<?php endif ?>
			         			<?php if ($pregunta->tipo == 2): //pregunta larga ?>
			         				<p class="text-justify">R: <?php echo $respuesta->descripcion; ?></p>
			         			<?php endif ?>
			         			<?php if ($pregunta->tipo == 3): ?>
				         				<p class="text-justify">R: <?php echo $respuesta->descripcion; ?></p>
			         			<?php endif ?>
			         			<?php if ($pregunta->tipo == 4): ?>
			         				<?php 
			         				$respuestas_usuario = '';
			         				$opciones = My_Comun::obtenerFiltroSQL('opciones_pregunta',' WHERE status=1 AND pregunta_id='.$pregunta->id,' opcion ASC '); 
			         				?>
			         				<?php foreach ($opciones as $opcion): ?>
					         			<?php $respuesta2 = Respuesta::obtieneRespuestaEspecial($opcion->opcion, $pregunta->id); ?>
			         					<?php if ($respuesta2->id!= ''){
			         						$respuestas_usuario .= $opcion->opcion.', ';
			         					 } ?>
			         				<?php endforeach ?>
			         				<?php $respuestas_usuario = substr($respuestas_usuario, 0, -2); ?>
				         				<p class="text-justify">R: <?php echo $respuestas_usuario; ?></p>
			         			<?php endif ?>
<!--			         				<input type="hidden" name="pregunta_id[<?php echo $pregunta->id; ?>]" value="<?php echo $pregunta->id; ?>">-->
			         		</div>
			         	</div>
			         <?php endforeach ?>
			         </div>
		         </div>
		         <?php $contador2++; ?>
	        <?php endforeach ?>
	        </div>
	      </div>
	      <!-- /tabs -->
	      
	    </div>

	    <br>    
	  	<?php if ($this->registro->id == ''): ?>
		    <div class="col-xs-12 text-right mb40px">
<!--		        <button class="btn btn-rojo-1" onclick="limpiar('frmContestaEncuesta');" type="button" ><i class="fa fa-eraser"></i> Limpiar</button>-->
		    </div>
	  	<?php endif ?>  
	</div>
</div>