<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
    Espere un momento, por favor...
    <div class="progress">
        <div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <span class="sr-only">100% Completo</span>
        </div>
    </div>
</div>

    <form id="frmPreRegistro" name="frmPreRegistro" class="form-horizontal" method="post" action="/backend/estado/guardar" role="form" enctype="multipart/form-data">    
    <br/>  

    <div class="col-xs-12 form-group"> 
        <label for="estado" class="col-xs-2 control-label"><span class="naranja">*</span>Descripci&oacute;n:</label>
        <div class="col-xs-4">
            <input type="text" id="estado" name="estado"  class="form-control input-sm text-capitalize required" value="<?php echo $this->registro->estado ?>"  maxlength="100" placeholder="Descripci&oacute;n" />
        </div>
    

    </div>
 

    <br>   
    <input type="hidden" name="status" id="status" value="1"> 
    
    <div class="col-xs-12 text-right">
    <input type="hidden" name="id_estado" id="id_estado" value="<?php echo $this->registro->id_estado; ?>" /> <!-- cuando no es nuevo -->
    <button class="btn btn-rojo-1" onclick="guardarPreregistro('frmPreRegistro','frmFiltrosPreRegistro','/backend/estado/grid','/backend/estado/imprimir','/estado/exportar');" type="button" ><i class="fa fa-check-circle"></i> Aceptar</button>
    <button class="btn btn-rojo-1" onclick="cancelar();" type="button" ><i class="fa fa-times-circle"></i> Cancelar</button>
    </div>
    <br/><br/><br/>  

</form>