<div class="panel panel-default" style="margin: 5px 0;">
    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Personas</h3>
        <button type="button" onclick="agregar('/backend/persona/agregar', 0, 'frmPersona','Registrar Persona');" class="btn btn-sm btn-default pull-right <?php echo($this->puedeAgregar?"":"hide"); ?>">
            <i class="fa fa-plus"></i>&nbsp;Agregar
        </button>
    </div>
    <div class="panel-body">
        <form name="frmFiltrosPersona" id="frmFiltrosPersona">
            <div class="row margin-bottom-3">
                
                <div class="col-xs-2">
                    <label for="fnombre" class="sr-only">Nombre</label>
                    <input type="text" name="nombre" id="fnombre" class="form-control input-sm" value="" placeholder="Buscar nombre"/>
                </div>
                <div class="col-xs-2">
                    <label for="fpaterno" class="sr-only">Paterno</label>
                    <input type="text" name="paterno" id="fpaterno" class="form-control input-sm" value="" placeholder="Buscar apellido paterno"/>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Materno</label>
                    <input type="text" name="materno" id="fmaterno" class="form-control input-sm" value="" placeholder="Buscar apellido materno"/>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Estados</label>
                    <select name="estado_idS" id="estado_idS" class="form-control input-sm " onchange="cambiaEstado(this);">
                    <option value="">Selecciona un estado</option>
			    		<?php foreach ($this->estados as $estado): ?>
                        <?php  echo "<script>console.log( 'estados ids: " . $estado->estadoId . "' );</script>"; ?>
			    			<option value="<?php echo $estado->estadoId ?>"><?php echo $estado->estado; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Zonas</label>
                    <select name="zona_idS" id="zona_idS" class="form-control input-sm " onchange="cambiaZona(this);">
                    <option value="">Selecciona una zona</option>
			    		<!-- <?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?> -->
			    	</select>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Tipo</label>
                    <select name="tipo_idS" id="tipo_idS" class="form-control input-sm " onchange="cambiaTipo(this);">
                    <option value="">Selecciona un Tipo</option>
			    		<!-- <?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?> -->
			    	</select>
                </div>
    	    </div>
            <div class="row margin-bottom-2">
                <div class="col-xs-3 text-left">
                        <button class="btn btn-sm btn-default" type="button" onclick="filtrar('frmFiltrosPersona','/backend/persona/grid','/backend/persona/imprimir','/backend/persona/exportar');">
                            <i class="fa fa-search"></i>&nbsp;Filtrar
                        </button>
                        <button class="btn btn-sm btn-default" type="button" onclick="limpiar('frmFiltrosPersona','/backend/persona/grid');">
                            <i class="fa fa-eraser"></i>&nbsp;Limpiar
                        </button>
                    </div>
                </div>
            <div class="row margin-bottom-2">
            </div>
        </form>
    </div>
</div>
<div id="flexigrid"></div>
<div class="height-5"></div>