<!DOCTYPE html>
<html lang="es">
    <head>
    <meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Sistema Administrativo</title>
	<link rel="stylesheet" type="text/css" href="/recursos/jquery_ui_1_11_4/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/bootstrap/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/flexigrid/flexigrid.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/normalize/normalize_3_0_3.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/font-awesome-4-6-3/css/font-awesome.css" />
	<link rel="stylesheet" type="text/css" href="/css/comun.css" />
	<link rel="stylesheet" type="text/css" href="/css/backend.css" />


	<?php echo $this->headLink(); ?>
    </head>
    <body>
	<div class="container-floud">
        
	<div class="container-floud">
        <header class="banner"> 	
            <div class="encabezado">
			<div class="container">
                <figure class="pull-left">
                    <img src="/img/logo_ca.png" class="logo img-rounded" alt="" title="" />
                </figure>
			
                <!-- <div class="row col-xs-4"> -->
                    <!--<h1 class="mt60px bold f24px text-center">RESSUDI</h1>-->
                <!-- </div> -->
	
                <div class="btn-group pull-right menu">

				<div class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>&nbsp;Mi Perfil<span class="caret"></span></button>
							<ul class="dropdown-menu text-left" role="menu">
								<?php if(My_Comun::tienePermiso("VER_MIS_DATOS")){ ?><li><a href="/backend/mis-datos/mis-datos"> <i class="fa fa-user-o"></i>&nbsp;Datos básicos &nbsp; </a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_MI_CURRICULUM")){ ?><li><a href="/backend/mi-curriculum/mi-curriculum"> <i class="fa fa-address-card"></i>&nbsp;Currículum  &nbsp; </a></li> <?php } ?>
								</ul>
                </div>
	

					<!-- <?php if(My_Comun::tienePermiso("VER_MIS_DATOS")){ ?><a class="btn btn-default " href="/backend/mis-datos/mis-datos"> <i class="fa fa-user"></i>&nbsp;Mi Perfil &nbsp; </a><?php } ?> -->
					<!-- <?php if(My_Comun::tienePermiso("VER_MIS_DATOS")){ ?><a class="btn btn-default" href="javascript:_usuario('<?php echo Zend_Auth::getInstance()->getIdentity()->id ?>')"> <i class="fa fa-user"></i>&nbsp;Mi Perfil &nbsp; </a><?php } ?> -->
					<?php if(My_Comun::tienePermiso("VER_MI_EMPRESA")){ ?><a class="btn btn-default" href="/backend/mi-empresa/empresa-usuario"><i class="fa fa-building-o"></i>&nbsp;Mi Empresa &nbsp;</a><?php } ?>
	                <div class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-list-alt"></i>&nbsp;Administraci&oacute;n<span class="caret"></span></button>
							<ul class="dropdown-menu text-left" role="menu">
								<?php if(My_Comun::tienePermiso("VER_BITACORA")){ ?><li><a href="/backend/bitacora"><i class="fa fa-th-list"></i>&nbsp;Bit&aacute;cora</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_USUARIO")){ ?><li><a href="/backend/usuario"><i class="fa fa-male"></i>&nbsp;Usuarios</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_TIPO_USUARIO")){ ?><li><a href="/backend/tipo-usuario"><i class="fa fa-male"></i>&nbsp;Tipos de usuarios</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_PERSONA")){ ?><li><a href="/backend/persona"><i class="fa fa-users"></i>&nbsp;Personas</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_PRE_REGISTRO")){  ?><li><a href="/backend/pre-registro"><i class="fa fa-id-card"></i>&nbsp;Pre-registros &nbsp;</a></li> <?php } ?>
	                    	</ul>
					</div>
	                <div class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-industry"></i>&nbsp;Empresas<span class="caret"></span></button>
							<ul class="dropdown-menu text-left" role="menu">
								<?php if(My_Comun::tienePermiso("VER_EMPRESA")){ ?><li><a href="/backend/empresa"><i class="fa fa-building-o"></i>&nbsp;Registro</a></li> <?php } ?>
	                    	</ul>
					</div>
	                <div class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-list-alt"></i>&nbsp;Encuestas<span class="caret"></span></button>
							<ul class="dropdown-menu text-left" role="menu">
								<?php if(My_Comun::tienePermiso("VER_ENCUESTAS")){ ?><li><a href="/backend/encuestas"><i class="fa fa-pencil-square-o"></i>&nbsp;Registrar</a></li> <?php }  ?>
								<?php if(My_Comun::tienePermiso("VER_CONTESTA_ENCUESTA")){ ?><li><a href="/backend/contesta-encuesta"><i class="fa fa-pencil"></i>&nbsp;Contestar </a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_CONTESTA_ENCUESTA")){ ?><li><a href="/backend/contesta-encuesta/visualizar-encuestas"><i class="fa fa-file-text-o"></i>&nbsp;Visualizar&nbsp;</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_ASIGNA_ENCUESTA")){ ?><li><a href="/backend/asigna-encuesta" ><i class="fa fa-bookmark-o"></i>&nbsp;Asignaci&oacute;n</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_PREGUNTAS")){ ?><li><a href="/backend/preguntas"><i class="fa fa-question"></i>&nbsp;Preguntas</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_CATEGORIA")){ ?><li><a href="/backend/categoria"><i class="fa fa-star-o"></i>&nbsp;Categor&iacute;as</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_ZONAS")){ ?><li><a href="/backend/zonas"><i class="fa fa-map-o"></i>&nbsp;Zonas</a></li> <?php } ?>
	                    	</ul>
					</div>
	                <a class="btn btn-default" href="http://<?php echo $_SERVER["SERVER_NAME"] ?>/backend/ingreso/salir">Salir &nbsp; <i class="fa fa-sign-out"></i> </a>
			
				</div>
				</div>
            </div>
	</header>
	</div>

	<div class="container-floud">
            <div class="row"><div class="col-xs-24"><?php echo $this->layout()->content; ?></div></div>
    </div>

	<?php 

		if($_SERVER['REQUEST_URI'] == "/backend/index" || $_SERVER['REQUEST_URI'] == "/backend" || $_SERVER['REQUEST_URI'] == "/backend/"){
			
		}else{
			echo '<footer id="footer2">
			</footer>';
		}
	?>
    
	<input type="hidden" name="_peticion" id="_peticion" value="<?php echo $this->peticion; ?>" />
	<input type="hidden" name="_modulo" id="_modulo" value="<?php echo $this->modulo; ?>" />
	<input type="hidden" name="_controlador" id="_controlador" value="<?php echo $this->controlador; ?>" />
	<input type="hidden" name="_accion" id="_accion" value="<?php echo $this->accion; ?>" />

	<div id="_dialogo-1" class="display-none"></div>
	<div id="_dialogo-2" class="display-none"></div>
    <div id="_dialogo-3" class="display-none"></div>
	<div id="_dialogo-pausa-notificacion" class="display-none"></div>
	<div id="_mensaje-1" class="display-none"></div>
	<div id="_mensaje-2" class="display-none"></div>
    <div id="_mensaje-3" class="display-none"></div>
		
	<!-- La carga de los scripts debe hacerse al final -->
	<script src="/recursos/jquery_2_2_1/jquery2_2_1.js"></script>
	<script src="/recursos/jquery_ui_1_11_4/jquery-ui.js"></script>
	<script src="/recursos/bootstrap/bootstrap.js"></script>
	<script src="/recursos/flexigrid/flexigrid.js"></script>
	<script src="/recursos/jquery_form_3_18/ajaxforms.js"></script>
	<script src="/recursos/jquery_validation_1_13_0/dist/jquery.validate.min.js"></script>    
	<script src="/recursos/jquery_validation_1_13_0/dist/localization/messages_es.min.js"></script>    
	
	<script src="/js/backend/comun.js"></script>
	<?php echo $this->headScript(); ?>        
    </body>
	</div>
	<footer class="footer">
        <p>© 2018 UTJ, edu.</p>
      </footer>
</html>