<!DOCTYPE html>
<html lang="es">
    <head>
    <meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Sistema Administrativo</title>
	<link rel="stylesheet" type="text/css" href="/recursos/jquery_ui_1_11_4/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/bootstrap/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/flexigrid/flexigrid.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/normalize/normalize_3_0_3.css" />
	<link rel="stylesheet" type="text/css" href="/recursos/font-awesome-4-6-3/css/font-awesome.css" />
	<!-- <link rel="stylesheet" type="text/css" href="/recursos/font-awesome-5-0-13/css/fontawesome-all.css" /> -->
	<link rel="stylesheet" type="text/css" href="/css/comun.css" />
	<link rel="stylesheet" type="text/css" href="/css/backend.css?<?php echo time(); ?>" />
	<?php echo $this->headLink(); ?>

	<style>

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #3e8e41;}
</style>

    </head>
    <body>
        <div id="mainContent">
        <header class="banner">

            <div class="encabezado">
                <figure class="pull-left">
                    <img src="/img/logo_ca2.png" class="logo" alt="" title="" />
                </figure>

                <div class="row col-xs-4">
                    <!--<h1 class="mt60px bold f24px text-center">RESSUDI</h1>-->
                </div>
	






                <div class="btn-group pull-right menu">
<?php if(My_Comun::tienePermiso("VER_INICIO")){ ?><a class="btn btn-default" href="/backend/index"> <i class="fa fa-home"></i>&nbsp;Inicio &nbsp; </a><?php } ?>


					<?php if(My_Comun::tienePermiso("VER_MIS_DATOS")){ ?><a class="btn btn-default" href="/backend/mis-datos/mis-datos"> <i class="fa fa-user"></i>&nbsp;Mi Perfil &nbsp; </a><?php } ?>
<!--					<?php if(My_Comun::tienePermiso("VER_MIS_DATOS")){ ?><a class="btn btn-default" href="javascript:_usuario('<?php echo Zend_Auth::getInstance()->getIdentity()->id ?>')"> <i class="fa fa-user"></i>&nbsp;Mi Perfil &nbsp; </a><?php } ?> -->
					<?php if(My_Comun::tienePermiso("VER_MI_EMPRESA")){ ?><a class="btn btn-default" href="/backend/mi-empresa/empresa-usuario"><i class="fa fa-building-o"></i>&nbsp;Mi Empresa &nbsp;</a><?php } ?>
	                	<?php if (My_Comun::tienePermiso("VER_BITACORA") || My_Comun::tienePermiso("VER_USUARIO") || My_Comun::tienePermiso("VER_TIPO_USUARIO") || My_Comun::tienePermiso("VER_PERSONA") || My_Comun::tienePermiso("VER_PRE_REGISTRO")): ?>
		                <div class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-list-alt"></i>&nbsp;Administraci&oacute;n<span class="caret"></span></button>
								<ul class="dropdown-menu text-left" role="menu">

								<?php if(My_Comun::tienePermiso("VER_USUARIO")){ ?><li><a href="/backend/usuario"><i class="fa fa-male"></i>&nbsp;Usuario</a></li> <?php } ?>
								<?php if(My_Comun::tienePermiso("VER_PERSONA")){ ?><li><a href="/backend/persona"><i class="fa fa-users"></i>&nbsp;Persona</a></li> <?php } ?>	
                                <?php if(My_Comun::tienePermiso("VER_PRE_REGISTRO")){  ?><li><a href="/backend/pre-registro"><i class="fa fa-id-card"></i>&nbsp;Pre-registro &nbsp;</a></li> <?php } ?>
                                <?php if(My_Comun::tienePermiso("VER_MENSAJE")){  ?><li><a href="/backend/mensaje"><i class="fa fa-envelope"></i>&nbsp;Mensaje &nbsp;</a></li> <?php } ?>
									<?php if(My_Comun::tienePermiso("VER_BITACORA")){ ?><li><a href="/backend/bitacora"><i class="fa fa-th-list"></i>&nbsp;Bit&aacute;cora</a></li> <?php } ?>
									<?php if(My_Comun::tienePermiso("VER_TIPO_PERSONA")){  ?><li><a href="/backend/tipo-persona"><i class="fa fa-id-badge"></i>&nbsp;Tipo Persona &nbsp;</a></li> <?php } ?>
									<?php if(My_Comun::tienePermiso("VER_ESTADO")){  ?><li><a href="/backend/estado"><i class="fa fa-globe"></i>&nbsp;Estados &nbsp;</a></li> <?php } ?>


									<?php if(My_Comun::tienePermiso("VER_TIPO_USUARIO")){ ?><li><a href="/backend/tipo-usuario"><i class="fa fa-street-view"></i>&nbsp; Tipo usuarios</a></li> <?php } ?>
									
									
									
									<?php if(My_Comun::tienePermiso("VER_EDITARMENSAJE")){  ?><li><a href="/backend/editarMensaje"><i class="fa fa-envelope"></i>&nbsp;Cat&aacute;logo Mensajes &nbsp;</a></li> <?php } ?>	
		                    	</ul>
						</div>
                	<?php endif ?>




                	<?php if (My_Comun::tienePermiso("VER_EMPRESA")): ?>
		                <div class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-university"></i>&nbsp;Empresa<span class="caret"></span></button>
								<ul class="dropdown-menu text-left" role="menu">
									<?php if(My_Comun::tienePermiso("VER_EMPRESA")){ ?><li><a href="/backend/empresa"><i class="fa fa-pencil"></i>&nbsp;Registro</a></li> <?php } ?>
									
									


									<?php if(My_Comun::tienePermiso("VER_AREAPROY")){  ?><li><a href="/backend/areaproy"><i class="fa fa-bookmark"></i>&nbsp;Cat&aacute;logo Areas&nbsp;</a></li> <?php } ?>
									<?php if(My_Comun::tienePermiso("VER_PROYECTO")){  ?><li><a href="/backend/proyecto"><i class="fa fa-tasks"></i>&nbsp;Cat&aacute;logo Proyectos &nbsp;</a></li> <?php } ?>
									
		                    	</ul>
						</div>
                	<?php endif ?>



                	<?php if (My_Comun::tienePermiso("VER_CONCENTRADOPROY")): ?>
		                <div class="btn-group">
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-tasks"></i>&nbsp;Proyectos<span class="caret"></span></button>
								<ul class="dropdown-menu text-left" role="menu">
									
									<?php if(My_Comun::tienePermiso("VER_CONCENTRADOPROY")){  ?><li><a href="/backend/concentradoProy"><i class="fa fa-address-card-o"></i>&nbsp;Visualizar &nbsp;</a></li> 	
									
									
									<?php } ?>
		                    	</ul>
						</div>
                	<?php endif ?>






	                <div class="btn-group">
						<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-clipboard"></i>&nbsp;Indicadores<span class="caret"></span></button>
							<ul class="dropdown-menu text-left" role="menu">
							<?php if(My_Comun::tienePermiso("VER_CONCENTRADO")){ ?><li><a href="/backend/concentrado"><i class="fa fa-address-card-o"></i>&nbsp;Concentrado</a></li> <?php }  ?>
							
							<?php if(My_Comun::tienePermiso("VER_CONTESTA_ENCUESTA")){ ?><li><a href="/backend/contesta-encuesta"><i class="fa fa-pencil-square-o"></i>&nbsp;Contestar </a></li> <?php } ?>
							<!-- <?php if(My_Comun::tienePermiso("VER_CONTESTA_ENCUESTA")){ ?><li><a href="/backend/contesta-encuesta/visualizar-encuestas"><i class="fa fa-file-text-o"></i>&nbsp;Visualizar&nbsp;</a></li> <?php } ?> --> 
							<?php if(My_Comun::tienePermiso("VER_ASIGNA_ENCUESTA")){ ?><li><a href="/backend/asigna-encuesta" ><i class="fa fa-bookmark-o"></i>&nbsp;Asignaci&oacute;n</a></li> <?php } ?>	<?php if(My_Comun::tienePermiso("VER_CATEGORIA")){ ?><li><a href="/backend/categoria"><i class="fa fa-star-o"></i>&nbsp;Cat&aacute;logo Categor&iacute;as</a></li> <?php } ?>
							<?php if(My_Comun::tienePermiso("VER_ENCUESTAS")){ ?><li><a href="/backend/encuestas"><i class="fa fa-pencil"></i>&nbsp;Cat&aacute;logo Encuestas</a></li> <?php }  ?>
							
							<?php if(My_Comun::tienePermiso("VER_PREGUNTAS")){ ?><li><a href="/backend/preguntas"><i class="fa fa-question"></i>&nbsp;Cat&aacute;logo Preguntas</a></li> <?php } ?>
							
							<?php if(My_Comun::tienePermiso("VER_ZONAS")){ ?><li><a href="/backend/zonas"><i class="fa fa-map-o"></i>&nbsp;Cat&aacute;logo Zonas</a></li> <?php } ?>
	                    	</ul>
					</div>
	                <a class="btn btn-default" href="http://<?php echo $_SERVER["SERVER_NAME"] ?>/backend/ingreso/salir">Salir &nbsp; <i class="fa fa-sign-out"></i> </a>
            </div>
	</header>

	<div class="container">
            <div class="row"><div class="col-xs-24"><?php echo $this->layout()->content; ?></div></div>
    </div>

	<?php 

		if($_SERVER['REQUEST_URI'] == "/backend/index" || $_SERVER['REQUEST_URI'] == "/backend" || $_SERVER['REQUEST_URI'] == "/backend/"){
			
		}else{
			echo '<footer id="footer2">
			</footer>';
		}
	?>
    
	<input type="hidden" name="_peticion" id="_peticion" value="<?php echo $this->peticion; ?>" />
	<input type="hidden" name="_modulo" id="_modulo" value="<?php echo $this->modulo; ?>" />
	<input type="hidden" name="_controlador" id="_controlador" value="<?php echo $this->controlador; ?>" />
	<input type="hidden" name="_accion" id="_accion" value="<?php echo $this->accion; ?>" />

	<div id="_dialogo-1" class="display-none"></div>
	<div id="_dialogo-2" class="display-none"></div>
    <div id="_dialogo-3" class="display-none"></div>
	<div id="_dialogo-pausa-notificacion" class="display-none"></div>
	<div id="_mensaje-1" class="display-none"></div>
	<div id="_mensaje-2" class="display-none"></div>
    <div id="_mensaje-3" class="display-none"></div>
		
	<!-- La carga de los scripts debe hacerse al final -->
	<!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
	<script src="/recursos/jquery_2_2_1/jquery.min.js"></script>
	<script src="/recursos/jquery_2_2_1/jquery2_2_1.js"></script>
	<script src="/recursos/jquery_ui_1_11_4/jquery-ui.js"></script>
	<script src="/recursos/bootstrap/bootstrap.js"></script>
	<script src="/recursos/flexigrid/flexigrid.js"></script>
	<script src="/recursos/jquery_form_3_18/ajaxforms.js"></script>
	<script src="/recursos/jquery_validation_1_13_0/dist/jquery.validate.min.js"></script>    
	<script src="/recursos/jquery_validation_1_13_0/dist/localization/messages_es.min.js"></script>    
	<script src="/recursos/idle/jquery.idle.js"></script>
	<script src="/js/backend/comun.js"></script>

	<script type="text/javascript">
	$(window).load(function(){

	$('.menu li a').click(function (e) {     
		//get selected href
		var href = $(this).attr('href');    
		// console.log(href);

		$('.tabs-left').hide();
		$('.tabs-left'+href).show();
		
		//set all nav tabs to inactive
		// $('.nav-tabs li').removeClass('active');
		// $('.nav-tabs li a[href="'+href+'"]').addClass('active');
		
		//get all nav tabs matching the href and set to active
		// $('.tabs-left [href="'+href+'"]').addClass('active');
		// $('.tabs-left li a[href="'+href+'"]').addClass('active');

		//active tab
		// $('.tabs-left').removeClass('active');
		// $('.tabs-left'+href).addClass('active');
	})
	});
	</script>






	<?php echo $this->headScript(); ?>   
	</div>     
    </body>
</html>