<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- Quitar los responsivo -->
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
        <meta name="description" content="Toma Nota">
        <title>Sistema::Administrativo</title>
        <link rel="stylesheet" type="text/css" href="/recursos/jquery_ui_1_11_4/jquery-ui.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/bootstrap/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/flexigrid/flexigrid.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/normalize/normalize_3_0_3.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/font-awesome-4-6-3/css/font-awesome.css" />
        <link rel="stylesheet" type="text/css" href="/css/comun.css" />
        <link rel="stylesheet" type="text/css" href="/css/backend.css" />
        <link rel="stylesheet" type="text/css" href="/css/404.css" />
        <link href='https://fonts.googleapis.com/css?family=Anton|Passion+One|PT+Sans+Caption' rel='stylesheet' type='text/css'>
        <?php echo $this->headLink(); ?>

        <link rel="apple-touch-icon" sizes="180x180" href="/imagenes/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="/imagenes/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="/imagenes/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="/imagenes/manifest.json">
        <link rel="mask-icon" href="/imagenes/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon" href="/imagenes/favicon.ico">
        <meta name="msapplication-TileColor" content="#e21f19">
        <meta name="msapplication-TileImage" content="/imagenes/mstile-144x144.png">
        <meta name="msapplication-config" content="/imagenes/browserconfig.xml">
        <meta name="theme-color" content="#ffffff">

    </head>
    <body>
        <section role="main">
            <div class="container-floud">
                <?php echo $this->layout()->content; ?>
            </div>                                
        </section>

        <input type="hidden" name="_peticion" id="_peticion" value="<?php echo $this->peticion; ?>" />
        <input type="hidden" name="_modulo" id="_modulo" value="<?php echo $this->modulo; ?>" />
        <input type="hidden" name="_controlador" id="_controlador" value="<?php echo $this->controlador; ?>" />
        <input type="hidden" name="_accion" id="_accion" value="<?php echo $this->accion; ?>" />

        <div id="_dialogo-1" class="display-none"></div>
        <div id="_dialogo-2" class="display-none"></div>
        <div id="_dialogo-pausa-notificacion" class="display-none"></div>
        <div id="_mensaje-1" class="display-none"></div>
        <div id="_mensaje-2" class="display-none"></div>
        
        <!-- La carga de los scripts debe hacerse al final -->
        <script src="/recursos/jquery_2_2_1/jquery2_2_1.js"></script>
        <script src="/recursos/jquery_ui_1_11_4/jquery-ui.js"></script>
        <script src="/recursos/bootstrap/bootstrap.js" />
        <script src="/recursos/flexigrid/flexigrid.js"></script>
        <script src="/recursos/jquery_form_3_18/ajaxforms.js"></script>
        <script src="/recursos/jquery_validation_1_13_0/dist/jquery.validate.min.js"></script>    
        <script src="/recursos/jquery_validation_1_13_0/dist/localization/messages_es.min.js"></script>   
        <script src="/js/backend/comun.js"></script>
        <script src="/js/backend/ingreso.js"></script>
        <script src="/recursos/404/numbers.js"></script>
        <?php echo $this->headScript(); ?>      


    </body>
</html>