<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- Quitar los responsivo -->
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
        <title>Sistema::Ingreso</title>
        <link rel="stylesheet" type="text/css" href="/recursos/jquery_ui_1_11_4/jquery-ui.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/bootstrap/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/flexigrid/flexigrid.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/normalize/normalize_3_0_3.css" />
        <link rel="stylesheet" type="text/css" href="/recursos/font-awesome-4-6-3/css/font-awesome.css" />
        <link rel="stylesheet" type="text/css" href="/css/comun.css" />
        <link rel="stylesheet" type="text/css" href="/css/backend.css" />

        <?php echo $this->headLink(); ?>
    
    </head>
    <body>

<!--        <header class="banner">
            <div class="encabezado">
                <figure class="pull-left">
                    <img src="/img/logo_ca.png" class="logo"  />
                </figure>
                <div class="row">
                    <center><h1 class="mt40px bold f24px">Administración RESSUDI</h1></center>
                </div>
            </div>
        </header>
-->
<header id="header">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">CA02UTJ</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/index">Inicio</a></li>
                    <li><a href="/index/about">Acerca de...</a></li>
                    <li><a href="/index/contact">Contactanos</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
              <li><a href="/index/pre-register" id="registerLink">Registro</a></li>
              <li><a href="/backend" id="loginLink">Acceso al sistema</a></li>
          </ul>
            </div>
        </div>
    </div>
</header>

        <div class="container">
            <div class="row">
                <div class="col-xs-offset-4 col-xs-4">
                    <div class="panel panel-default" style="margin-top: 80px;">
                        <div class="pnl-heading-rojo-1">
                            <h3 class="panel-title"><i class="fa fa-user"></i>&nbsp; Ingreso</h3>
                        </div>
                        
                        <div class="panel-body">
                            <div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
                                Espere un momento, por favor...
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                        <span class="sr-only">100% Completo</span>
                            </div>
                                </div>
                            </div>
                        
                            <form id="frm-1" name="frm-1" method="post" action="/backend/ingreso/ingresar" role="form">
                                <div class="form-group">
                                    <!--<label for="correo_electronico" class="sr-only">*N&uacute;mero de empleado:</label>-->
                            <!--<input type="text" id="numero" name="numero" class="form-control required number" value="" placeholder="N&uacute;mero de empleado">-->
                                                    
                            <input type="text" id="usuario" name="usuario" class="form-control required" value="" placeholder="Usuario">                
                                </div>
                                
                                <div class="form-group">
                                    <label for="contrasena" class="sr-only">*Contrase&ntilde;a:</label>
                                    <input type="password" id="contrasena" name="contrasena" class="form-control required" value="" placeholder="Contrase&ntilde;a">
                                </div>
                                <br />
                                
                                <button type="submit" class="btn btn-rojo-1 pull-right naran">
                                    <i class="fa fa-sign-in "></i>
                                    Ingresar
                                </button>
                                <br/><br/><br/>
                        
                           <button type="button" class="btn btn-link" onclick="recupera();" style="position: relative; margin: auto; width:90% ">
                                <i class="fa fa-key"></i> Recuperar contrase&ntilde;a
                            </button>
                            </form>
                        </div>
                    </div>
                </div>                
            </div>
        </div>




        
        <footer>
            <div class="container body-content">
              <hr />
                  <div class="col-md-4">
                      <b>Universidad Tecnológica de Jalisco</b> <br />
                      <address>                    
                          División de Desarrollo e Innovación Empresarial <br />
                          Director de la División<br />
                          Lic. Jorge Sandoval Rodríguez <br />
                          Luis J. Jiménez #577 <br />
                          <abbr title="Telefono">Teléfonos: </abbr><br />
                          Conmutador: 30300900 Ext 7361 <br />
                          Directo:    30300926
                      </address>
                      
                      </div>
                  <div class="col-md-4">
                      <p>Desarrolladores del sistema <br /><br /> Edgardo E. González del Castillo <br /> Esa&uacute; Tolosa Carrillo <br /> Jose Luis Lagunes Gomez</p>
                  </div>
                  <div class="col-md-4 text-center">
                      <img src="/img/logo_ca.png" width="200" height="100" />
                  </div>
            </div>

        </footer>
        <input type="hidden" name="_peticion" id="_peticion" value="<?php echo $this->peticion; ?>" />
        <input type="hidden" name="_modulo" id="_modulo" value="<?php echo $this->modulo; ?>" />
        <input type="hidden" name="_controlador" id="_controlador" value="<?php echo $this->controlador; ?>" />
        <input type="hidden" name="_accion" id="_accion" value="<?php echo $this->accion; ?>" />

        <div id="_dialogo-1" class="display-none"></div>
        <div id="_dialogo-2" class="display-none"></div>
        <div id="_dialogo-pausa-notificacion" class="display-none"></div>
        <div id="_mensaje-1" class="display-none"></div>
        <div id="_mensaje-2" class="display-none"></div>
        
        <!-- La carga de los scripts debe hacerse al final -->
        <script src="/recursos/jquery_2_2_1/jquery2_2_1.js"></script>
        <script src="/recursos/jquery_ui_1_11_4/jquery-ui.js"></script>
        <script src="/recursos/bootstrap/bootstrap.js" />
        <script src="/recursos/flexigrid/flexigrid.js"></script>
        <script src="/recursos/jquery_form_3_18/ajaxforms.js"></script>
        <script src="/recursos/jquery_validation_1_13_0/dist/jquery.validate.min.js"></script>    
        <script src="/recursos/jquery_validation_1_13_0/dist/localization/messages_es.min.js"></script>   
        <script src="/js/backend/comun.js"></script>
        <script src="/js/backend/ingreso.js"></script>
        <?php echo $this->headScript(); ?>                
    </body>
</html>