<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>Cuerpo Acad&eacute;mico 02</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--<link rel="icon" href="img/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />-->

<!--CSS-->
  <link rel="stylesheet" type="text/css" href="/recursos/jquery_ui_1_11_4/jquery-ui.css" />
  <link rel="stylesheet" type="text/css" href="/css/bootstrap.css" />
<!--  <link rel="stylesheet" type="text/css" href="/recursos/bootstrap/bootstrap.css" />-->
  <link rel="stylesheet" type="text/css" href="/recursos/flexigrid/flexigrid.css" />
  <link rel="stylesheet" type="text/css" href="/recursos/normalize/normalize_3_0_3.css" />
  <link rel="stylesheet" type="text/css" href="/recursos/font-awesome-4-6-3/css/font-awesome.css" />
<!--  <link rel="stylesheet" type="text/css" href="/css/comun.css" />-->
<!--  <link rel="stylesheet" type="text/css" href="/css/backend.css" />-->
  <link rel="stylesheet" type="text/css" href="/css/site.css" />


 <?php echo $this->headLink(); ?>
 
</head>
<body style= "background-image: url('/img/fondoUTJ1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center; background-attachment: fixed;">
<!--header-->
<header id="header">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">CA02UTJ</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/index">Inicio</a></li>
                    <li><a href="/index/about">Acerca de...</a></li>
                    <li><a href="/index/contact">Contactanos</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
              <li><a href="/recursos/manuales/ManualEncuestas.pdf" target="_blank" >Manual de Usuario</a></li>
              <li><a href="/index/pre-register" id="registerLink">Registro</a></li>
              <li><a href="/backend" id="loginLink">Acceso al sistema</a></li>
          </ul>
            </div>
        </div>
    </div>
</header>

	<?php echo $this->layout()->content; ?>
<?php if ($_SERVER['REQUEST_URI'] != "/ingreso/recupera"): ?>
  <footer >
      <div class="container body-content">
        <hr />
            <div class="col-md-4">
           
                <b>División Económico Administrativa</b>

                 <br />
                <p>Desarrolladores del sistema <br /> <br /> Karina Cuevas Valdovinos <br />Edgardo E. González del Castillo</p>
                Modulos
                <br />Capital Intelectual - Esaú Tolosa Carrillo<br /> Planeación Estratégica - Saverio Soto Caloca<br />
                

              </div>
            <div class="col-md-4">
              <b>Agradecimientos </b></br>
              
              Consultoría</br>
              &nbsp; &nbsp;María de Lourdes Espinoza Aguilar</br>
              &nbsp; &nbsp;Investigación y Formación para el desarrollo social </br>&nbsp; &nbsp;sustentable</br>
 Estadía Empresarial</br>
              &nbsp; &nbsp;José Luis Lagunes Gómez </br>
              </br> © 2017 Responsabilidad Social, Sustentabilidad y Desarrollo Integral para PyMES
              

            </div>
            <div class="col-md-4">
            <img src="/img/cmic.png" width="180" height="40" align="center" /> &nbsp; &nbsp;
                <img src="/img/logo_ca2.png" width="140" height="70" />  &nbsp; &nbsp; &nbsp; &nbsp;
                <!--<img src="/img/esr.png" width="60" height="60" />-->
               </br>  </br> 
               Luis J. Jiménez 577, Colonia Primero de Mayo, C.P. 44979 Guadalajara, Jalisco, México 
                </br> Teléfono: + 52 (33) 3030-0900, 01, 02, 03


            </div>
    </div>
  </footer>
<?php endif ?>


  <input type="hidden" name="_peticion" id="_peticion" value="<?php echo $this->peticion; ?>" />
	<input type="hidden" name="_modulo" id="_modulo" value="<?php echo $this->modulo; ?>" />
	<input type="hidden" name="_controlador" id="_controlador" value="<?php echo $this->controlador; ?>" />
	<input type="hidden" name="_accion" id="_accion" value="<?php echo $this->accion; ?>" />

  <div id="_dialogo-1" class="display-none"></div>

  <div id="_mensaje-3" class="display-none"></div>


  <!-- La carga de los scripts debe hacerse al final -->
  <script src="/recursos/jquery_2_2_1/jquery2_2_1.js"></script>
  <script src="/recursos/jquery_ui_1_11_4/jquery-ui.js"></script>
  <script src="/js/modernizr-2.6.2.js"></script>
  <script src="/js/bootstrap.js"></script>
  <script src="/js/respond.js"></script>
  <script src="/recursos/flexigrid/flexigrid.js"></script>
  <script src="/recursos/jquery_form_3_18/ajaxforms.js"></script>
  <script src="/recursos/jquery_validation_1_13_0/dist/jquery.validate.min.js"></script>    
  <script src="/recursos/jquery_validation_1_13_0/dist/localization/messages_es.min.js"></script>    
  
  <script src="/js/backend/comun.js"></script>
  <?php echo $this->headScript(); ?>        

	<!--[if lt IE 9]>
	    <div style='text-align:center'><a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div>  
	  <![endif]-->
	<!--[if lt IE 9]><script src="../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	  <![endif]-->
</body>
</html>