<?php

/**
 * Persona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Persona{

    public static function obtenerPersonas()
    {
        $conec = new Conexion;
        $conexion = $conec->abreConexion();

        $sql = "SELECT p.id, p.nombre, p.apellido_pat, p.apellido_mat 
                  FROM persona p
                  WHERE id not in(
                    SELECT p.id
                    FROM persona p
                    inner join usuario u
                    on u.persona_id = p.id
                  )";
        $stmt = sqlsrv_query( $conexion, $sql);
        $datos = array();
        while( $obj = sqlsrv_fetch_object($stmt)) {
        
            $datos[] =  $obj;       
        }
        return $datos;
    }

    public static function ingresar($usuario,$contrasena){

        $conec = new Conexion;
        $conexion = $conec->abreConexion();
        $sql = "SELECT * FROM usuario WHERE usuario = '".$usuario."' AND contrasena='".$contrasena."'";

        $stmt = sqlsrv_query( $conexion, $sql);
        while( $obj = sqlsrv_fetch_object($stmt)) {
        
            return $obj;       
        }
    }

    public static function guardarPermisos($permisos,$id){
        $conec = new Conexion;
        $conexion = $conec->abreConexion();

        $cadena="";
        foreach($permisos as $permiso){
                $cadena.=(empty($cadena))?$permiso:"|".$permiso;
        }//foreach
        $consulta = "UPDATE dbo.usuario set permisos = '".$cadena."' WHERE id = ".$id;

            $s = sqlsrv_prepare($conexion, $consulta);

            try {
                sqlsrv_execute($s);
            } catch (Exception $e) {
                print_r($e);
                exit;
            }

//      Doctrine_Query::create()->update('Usuario')->set('permisos','?',$cadena)->where('id=?',$id)->execute();
        $regi=My_Comun::obtenerSQL("usuario", "id", $id);
        Bitacora::guardar('Usuario','Permisos de usuario',$regi->nombre);
    }//function


}