<?php

/**
 * Usuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Usuario{

/*    public static function ingresar($usuario){				
        try{
                    return Doctrine_Core::getTable('Usuario')->findOneByUsuario($usuario);
        	}catch(Doctrine_Exception $e){
                    return $e->getMessage();
	   }					
    }
*/
    public static function ingresar($usuario,$contrasena){

        $conec = new Conexion;
        $conexion = $conec->abreConexion();
        $sql = "SELECT * FROM usuario WHERE usuario = '".$usuario."' AND contrasena='".$contrasena."'";

        $stmt = sqlsrv_query( $conexion, $sql);
        while( $obj = sqlsrv_fetch_object($stmt)) {
        
            return $obj;       
        }
    }

    public static function guardarPermisos($permisos,$id){
        $conec = new Conexion;
        $conexion = $conec->abreConexion();

        $cadena="";
        foreach($permisos as $permiso){
                $cadena.=(empty($cadena))?$permiso:"|".$permiso;
        }//foreach
        $consulta = "UPDATE dbo.usuario set permisos = '".$cadena."' WHERE id = ".$id;

            $s = sqlsrv_prepare($conexion, $consulta);

            try {
                sqlsrv_execute($s);
            } catch (Exception $e) {
                print_r($e);
                exit;
            }

//      Doctrine_Query::create()->update('Usuario')->set('permisos','?',$cadena)->where('id=?',$id)->execute();
        $regi=My_Comun::obtenerSQL("usuario", "id", $id);
        Bitacora::guardar('Usuario','Permisos de usuario',$regi->nombre);
    }//function


    public static function obtieneZonaUsuario($usuario_id)
    {
        $conec = new Conexion;
        $conexion = $conec->abreConexion();
        $sql = "  SELECT z.id
                      FROM usuario u
                      INNER JOIN persona p
                      on p.id = u.persona_id
                      INNER JOIN tipo_usuario tu
                      on tu.id = u.tipo_usuario
                      INNER JOIN empresa e
                      on e.id = p.empresa_id
                      INNER JOIN zona z
                      on z.id = e.zona_id
                    WHERE u.id = ".$usuario_id;
        $stmt = sqlsrv_query( $conexion, $sql);
        while( $obj = sqlsrv_fetch_object($stmt)) {
        
            return $obj;       
        }
    }
}