<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
    Espere un momento, por favor...
    <div class="progress">
        <div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <span class="sr-only">100% Completo</span>
        </div>
    </div>
</div>

    <form id="frmPreRegistro" name="frmPreRegistro" class="form-horizontal" method="post" action="/backend/tipo-persona/guardar" role="form" enctype="multipart/form-data">    
    <br/>  

    <div class="col-xs-12 form-group"> 
        <label for="descripcion" class="col-xs-2 control-label"><span class="naranja">*</span>Descripci&oacute;n:</label>
        <div class="col-xs-4">
            <input type="text" id="descripcion" name="descripcion"  class="form-control input-sm required" value="<?php echo $this->registro->descripcion ?>"  maxlength="100" placeholder="Descripci&oacute;n" />
        </div>
    

    </div>
 


    <div class="col-xs-12 form-group mb40px">
        <label for="zona_id" class="col-xs-2 control-label"><span class="naranja">*</span>Zona:</label>
        <div class="col-xs-4">
            <select class="form-control input-sm required" name="zona_id" id="zona_id">
                <option value="" selected>Seleccione una zona</option>
                <?php foreach ($this->zonas2 as $zona): ?>
                    <option value="<?php echo $zona->zona_id; ?>" <?php echo (($zona->zona_id==$this->registro->zona_id)?'selected':'') ?>><?php echo $zona->znombre; ?></option>
                <?php endforeach ?>
            </select>
            
        </div>
    </div>
    <br>   
    <input type="hidden" name="status" value="1"> 
    
    <div class="col-xs-12 text-right">
    <input type="hidden" name="id" id="id" value="<?php echo $this->registro->id; ?>" /> <!-- cuando no es nuevo -->
    <button class="btn btn-rojo-1" onclick="guardarPreregistro('frmPreRegistro','frmFiltrosPreRegistro','/backend/pre-registro/grid','/backend/pre-registro/imprimir','/pre-registro/exportar');" type="button" ><i class="fa fa-check-circle"></i> Aceptar</button>
    <button class="btn btn-rojo-1" onclick="cancelar();" type="button" ><i class="fa fa-times-circle"></i> Cancelar</button>
    </div>
    <br/><br/><br/>  

</form>