

<div class="error">
    <div class="container-floud">
        <div class=" ground-color text-center">
            <div class="container-error-404">
                <div class="clip"><div class="shadow"><span class="digit thirdDigit"></span></div></div>
                <div class="clip"><div class="shadow"><span class="digit secondDigit"></span></div></div>
                <div class="clip"><div class="shadow"><span class="digit firstDigit"></span></div></div>
                <div class="msg">UPS!<span class="triangle"></span></div>
            </div>
            <h2 class="h1"><?php echo $this->message; ?></h2>
            <br>
            <p class="text-muted">Lo sentimos, pero parece que algo est&aacute; ocurriendo. No se preocupe, ya estamos trabajando para resolverlo.</p>
            <p class="text-muted">Mientras tanto, le pedimos que se dirija a nuestra p&aacute;gina de <a href="/index">inicio</a> y contin&uacute;e navegando.</p>
            <div class="col-sm-12  text-center">
            <?php
            if (isset($this->exception)){ ?>
                <h3>Informaci&oacute;n del error:</h3>
                <p><b>Mensaje:</b> <?php echo $this->exception->getMessage(); ?></p>
                <h3>Stack trace:</h3>
                <pre><?php echo $this->exception->getTraceAsString(); ?></pre>
                <h3>Par&aacute;metros de env&iacute;o:</h3>
                <pre><?php echo $this->escape(var_export($this->request->getParams(), true)); ?></pre>
            <?php
            } ?>
        </div>
        </div>
    </div>
</div>