
<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
	Espere un momento, por favor...
	<div class="progress">
		<div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			<span class="sr-only">100% Completo</span>
		</div>
	</div>
</div>

<script type="text/javascript">
	
function validars (){
    $("#frm-2").validate({
        submitHandler: function(form){
            $(form).ajaxSubmit({
                success: function(respuesta){
                    if(!isNaN(respuesta)){   
                        _mensaje("#_mensaje-1",  'Su mensaje ha sido enviado, gracias.' );
                        document.getElementById("usuario_destino").value = "";
						document.getElementById("mensaje").value = "";
						document.getElementById("asunto").value = "";
						document.getElementById("fecha_limite").value = "";
						document.getElementById("tipo_usuario").value = "";
                    }else{                       
                        _mensaje("#_mensaje-1",  respuesta );
                    }                        
                } //success
                ,error: function(respuesta){
                    _mensaje("#_mensaje-1", "Ocurri&oacute; un error inesperado, int&eacute;ntelo de nuevo");
                } //error
            }) //ajaxSubmit
        } //submitHandler
    }) //validate
    $("#frm-2").submit();    
}

</script>
<div class="panel panel-default" style="margin: 5px 0;">

    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Enviar Mensaje</h3>
    </div>

    <div class="panel-body">


	<form id="frm-2" name="frm-2" class="form-horizontal" method="post" action="/backend/mensaje/guardar-mensaje" role="form" >
	
	<div class="col-xs-12 form-group">
        <label for="tipo_usuario" class="col-xs-2 control-label"><span class="naranja">*</span>Tipo de Usuario:</label>
        <div class="col-xs-4">
            <select name="tipo_usuario" class="form-control required" id="tipo_usuario" onchange="cambiaTipoUsuario(this.value,<?php echo $this->zona[0]->id; ?>);">
                <option value="" selected>-- Seleccione tipo de usuario --</option>
                
                <?php foreach ($this->tipos_usuarios as $tipo_usuario): ?>
                    <option value="<?php echo $tipo_usuario->id ?>"><?php echo utf8_encode($tipo_usuario->descripcion) ?></option>
                <?php endforeach ?>
                <option value="0">Todos</option>
            </select>
        </div>
	        <label for="fecha_limite" class="col-xs-2 control-label"><span class="naranja">*</span>Fecha limite</label>
	        <div class="col-xs-4">
	        	<input type="text" name="fecha_limite" id="fecha_limite" class="form-control input-sm required" value="<?php echo date_format($this->mensaje->fecha_limite,'Y-m-d') ?>" placeholder="Fecha limite">    
	        </div>         
	          
	</div>

	<div class="col-xs-12 form-group">
		<label for="usuario_destino" class="col-xs-2 control-label"><span class="naranja">*</span>Enviar a:</label>
				<div class="col-xs-4">
							
							<select id="usuario_destino" name="usuario_destino" class="form-control required" >
									<option value="" selected>-- Seleccione usuario --</option>
			                <?php if (is_object($this->usu)): ?>
			                    <option value="<?php echo $this->usu->id; ?>" selected>
			                    <?php echo $this->usu->usuario; ?></option>	              
			                <?php endif; ?>
							</select>
				</div>
				<label for="asunto" class="col-xs-2 control-label"><span class="naranja">*</span>Asunto:</label>
				<div class="col-xs-4">							
					<input type="text" id="asunto" name="asunto" class="form-control input-sm required" value="" maxlength="250" placeholder="Asunto" />
				</div>
	</div>
     
		    <br><br>
		    <div class="form-group">
		      <label for="mensaje"><span class="naranja">*</span>Mensaje:</label>
		      <textarea class="form-control" rows="5" id="mensaje" name="mensaje" placeholder="Escriba su mensaje aqui..."></textarea>
		    </div>
		    <p><span class="naranja">*</span>Maximo 255 caracteres</p>
	</div>
    
    <div class="text-right"> 
    <input type="hidden" name="mensaje_id" id="mensaje_id" value="<?php echo $this->mensaje->id; ?>" /> <!-- cuando no es nuevo -->
    
        <button class="btn btn-rojo-1" onclick="validars();" type="button" ><i class="fa fa-floppy-o"></i> Enviar</button>
        <!--<button class="btn btn-rojo-1" onclick="cancelar();" type="button" ><i class="fa fa-times-circle"></i> Cancelar</button>-->
    </div>
    </form>




          
	
    </div>
<div id="flexigrid"></div>
<div class="height-5"></div>