<div class="container">
	<div class="panel-body">
	    <form id="frmAsignar" name="frmAsignar" class="form-horizontal" method="post" action="/backend/asigna-encuesta/guardar" role="form" enctype="multipart/form-data">    
	    <br/>
	    <div class="col-xs-12">
	    	<h4 class="text-center">Asignaci&oacute;n de encuestas por zonas</h4>
	    </div>
		    <div class="col-xs-12 form-group">

			<label class="col-xs-3 control-label">Selecciona una categoria</label>
		    	<div class="col-xs-3">
			    	<select name="categoria_id" id="categoria_id" class="form-control input-sm required" onchange="cambiaCategoria(this);">
			    		<!-- <option value="">Categoria</option> -->
			    		<?php foreach ($this->categorias as $categoria): ?>
			    			<option value="<?php echo $categoria->id ?>"><?php echo $categoria->nombre; ?></option>
			    		<?php endforeach ?>
			    	</select>
		    	</div>
				
		    	<label class="col-xs-2 control-label">Selecciona un estado</label>
		    	<div class="col-xs-4">
			    	<select name="estado_id" id="estado_id" class="form-control input-sm required" onchange="cambiaEstado(this);">
			    		<option value="">Estados</option>
			    		<?php foreach ($this->estados as $estado): ?>
			    			<option value="<?php echo $estado->id_estado ?>"><?php echo $estado->estado; ?></option>
			    		<?php endforeach ?>
			    	</select>
		    	</div>
		    </div>
			<br> 
			<input type="hidden" name="status" id="status" value="1"> 
			<!-- aqui cambio de row -->
			<div class="col-xs-12 form-group">
			<label class="col-xs-3 control-label">Selecciona una encuesta</label>
		    	<div class="col-xs-3">
			    	<select name="encuesta_id" id="encuesta_id" class="form-control input-sm required" onchange="">
			    		<!-- <option value="">Encuestas</option> -->
			    		<!-- <?php foreach ($this->encuestas as $encuesta): ?>
			    			<option value="<?php echo $encuesta->id ?>"><?php echo $encuesta->nombre; ?></option>
			    		<?php endforeach ?> -->
			    	</select>
		    	</div>
				<label class="col-xs-2 control-label">Selecciona una zona</label>
		    	<div class="col-xs-4">
			    	<select name="zona_id" id="zona_id" class="form-control input-sm required" onchange="cambiaZona();">
			    		<!-- <option value="">Zonas</option>
			    		<?php foreach ($this->zonas as $zona): ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?> -->
			    	</select>
		    	</div>
			</div>
			<!-- tercer row -->
			<div class="col-xs-12 form-group">
			<label class="col-xs-3 control-label"></label>
		    	<div class="col-xs-3">

		    	</div>
				<label class="col-xs-2 control-label">Selecciona un tipo</label>
		    	<div class="col-xs-4">
			    	<select name="tipo_id" id="tipo_id" class="form-control input-sm required" onchange="cambiaTipo(this);">
			    		<!-- <option value="">Tipo</option>
			    		<?php foreach ($this->zonas as $zona): ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?> -->
			    	</select>
		    	</div>
			</div>
			<!-- fin seccion general -->
		    <div class="col-xs-12 text-right mb40px">
		        <button class="btn btn-rojo-1" onclick="guardarAsignacion('frmAsignar');" type="button" ><i class="fa fa-floppy-o"></i> Guardar</button>
		        <button class="btn btn-rojo-1" onclick="limpiarAsinacion('frmAsignar');" type="button" ><i class="fa fa-eraser"></i> Limpiar</button>
		    </div>
		    <div class="col-xs-12 form-group">
		    <br>
		    	<h4 class="text-center">Zonas con encuestas</h4>
		    </div>
		    <div class="col-xs-12">
		    	<div id="flexigrid"></div>
		    </div>
		    <br>
		</form>	
	</div>
</div>