<div class="panel panel-default" style="margin: 5px 0;">
    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Usuarios</h3>
        <button type="button" onclick="agregar('/backend/usuario/agregar', 0, 'frm-1','Usuario');" class="btn btn-sm btn-default pull-right <?php echo($this->puedeAgregar?"":"hide"); ?>">
            <i class="fa fa-plus"></i>&nbsp;Agregar
        </button>
        <!-- <button type="button" onclick="agregar('/backend/usuario/agregar-zona', 0, 'frm-1','Agregar Zonas');" class="btn btn-sm btn-default pull-right <?php echo($this->puedeAgregar?"":"hide"); ?>">
            <i class="fa fa-plus"></i>&nbsp;Agregar Zonas
        </button> -->
    </div>
    <div class="panel-body">
        <form name="frmFiltrosUsuario" id="frmFiltrosUsuario">
            <div class="row margin-bottom-3">
                
                <div class="col-xs-3">
                <label for="fnombre" class="sr-only">Nombre</label>
                    <input type="text" name="nombre" id="fnombre" class="form-control input-sm" value="" placeholder="Buscar"/>
                </div>
                <div class="col-xs-2">
                <label for="fstatus" class="sr-only">Estatus</label>
                    <select id="fstatus" name="status" class="form-control input-sm">
                        <option value="">- Todos los estatus -</option>
                        <option value="1">Habilitado</option>
                        <option value="0">Deshabilitado</option>
                    </select>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Estados</label>
                    <select name="estado_id" id="estado_id" class="form-control input-sm " onchange="cambiaEstado(this);">
                    <option value="">Selecciona un estado</option>
                        <?php foreach ($this->estados as $estado): ?>
                        <?php  echo "<script>console.log( 'estados ids: " . $estado->estadoId . "' );</script>"; ?>
			    			<option value="<?php echo $estado->estadoId ?>"><?php echo $estado->estado; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Zonas</label>
                    <select name="zona_id" id="zona_id" class="form-control input-sm required" onchange="cambiaZona(this);">
                    <option value="">Selecciona una zona</option>
			    		<?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                <div class="col-xs-2">
                    <label for="fmaterno" class="sr-only">Tipo</label>
                    <select name="tipo_id" id="tipo_id" class="form-control input-sm required" onchange="cambiaTipo(this);">
                    <option value="">Selecciona un Tipo</option>
			    		<?php foreach ($this->zonas as $zona): ?>
                        <?php  echo "<script>console.log( 'Debug Objects: " . $zona->zona_id . "' );</script>"; ?>
			    			<option value="<?php echo $zona->zona_id ?>"><?php echo $zona->znombre; ?></option>
			    		<?php endforeach ?>
			    	</select>
                </div>
                
    	    </div>
            <div class="row margin-bottom-3">
            <div class="col-xs-4 ">
                   <button class="btn btn-sm btn-default" type="button" onclick="filtrar('frmFiltrosUsuario','/backend/usuario/grid','/backend/usuario/imprimir','/backend/usuario/exportar');">
                        <i class="fa fa-search"></i>&nbsp;Filtrar
                    </button>
                    <button class="btn btn-sm btn-default" type="button" onclick="limpiar('frmFiltrosUsuario','/backend/usuario/grid');">
                        <i class="fa fa-eraser"></i>&nbsp;Limpiar
                    </button>
                    <a id="btnImprimir" target="#" href="/backend/usuario/imprimir" class="btn btn-sm btn-default" >
                        <i class="fa fa-search"></i>&nbsp;Imprimir
                    </a>
                    <a id="btnExportar" target="_blank" href="/backend/usuario/exportar" class="btn btn-sm btn-default"  >
                        <i class="fa fa-eraser"></i>&nbsp;Exportar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="flexigrid"></div>
<div class="height-5"></div>