<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
	Espere un momento, por favor...
	<div class="progress">
		<div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			<span class="sr-only">100% Completo</span>
	</div>
	</div>
</div>
<form name="frm-1" id="frm-1" method="post" action="/backend/usuario/guardarpermisos">
	<div class="form-group"><label class="control-label">Nombre: <?php echo($this->nombre); ?></label></div>
	 
	<div class="form-group">
		<ul id="tabs" name="tabs" class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#seccion-1">Cat&aacute;logos</a></li>
		</ul>
		
		<div class="tab-content">
			<div id="seccion-1" class="tab-pane fade in active">
				<table class="table table-striped table-bordered table-hover table-condensed">
					<thead>
						<th>M&oacute;dulo</th>
						<th width="100">Ver</th>
						<th width="100">Agregar</th>
						<th width="100">Editar</th>
						<th width="100">Eliminar</th>
						<!--<th width="100">Documentos</th>-->
						<th width="100">Permisos</th>
					</thead>
                    
					<tbody>
						<tr>
							<td>Bit&aacute;cora</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_BITACORA" <?php echo (in_array("VER_BITACORA",$this->permisos))?"checked":""?> /></td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
							<!--<td align="center">&nbsp;</td>-->
							<td align="center">&nbsp;</td>
						</tr>
			
						<tr>
							<td>Usuario</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_USUARIO" <?php echo (in_array("VER_USUARIO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_USUARIO" <?php echo (in_array("AGREGAR_USUARIO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_USUARIO" <?php echo (in_array("EDITAR_USUARIO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_USUARIO" <?php echo (in_array("ELIMINAR_USUARIO",$this->permisos))?"checked":""?>/></td>
							<!--<td align="center"></td>-->
							<td align="center"><input type="checkbox" name="permisos[]" value="PERMISOS_USUARIO" <?php echo (in_array("PERMISOS_USUARIO",$this->permisos))?"checked":""?>/></td>
						</tr>
						<tr>
							<td>Tipo de usuario</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_TIPO_USUARIO" <?php echo (in_array("VER_TIPO_USUARIO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_TIPO_USUARIO" <?php echo (in_array("AGREGAR_TIPO_USUARIO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_TIPO_USUARIO" <?php echo (in_array("EDITAR_TIPO_USUARIO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_TIPO_USUARIO" <?php echo (in_array("ELIMINAR_TIPO_USUARIO",$this->permisos))?"checked":""?>/></td>
							<!--<td align="center"></td>-->
							<td align="center"></td>
						</tr>

						<tr>
							<td>Personas</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_PERSONA" <?php echo (in_array("VER_PERSONA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_PERSONA" <?php echo (in_array("AGREGAR_PERSONA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_PERSONA" <?php echo (in_array("EDITAR_PERSONA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_PERSONA" <?php echo (in_array("ELIMINAR_PERSONA",$this->permisos))?"checked":""?>/></td>
							<!--<td align="center"></td>-->
							<td align="center"><!--<input type="checkbox" name="permisos[]" value="PERMISOS_SECCION" <?php echo (in_array("PERMISOS_PERSONA",$this->permisos))?"checked":""?>/>--></td>
						</tr>

						<tr>
							<td>Preguntas</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_PREGUNTAS" <?php echo (in_array("VER_PREGUNTAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_PREGUNTAS" <?php echo (in_array("AGREGAR_PREGUNTAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_PREGUNTAS" <?php echo (in_array("EDITAR_PREGUNTAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_PREGUNTAS" <?php echo (in_array("ELIMINAR_PREGUNTAS",$this->permisos))?"checked":""?>/></td>
							<!--<td align="center"></td>-->
							<td align="center"><!--<input type="checkbox" name="permisos[]" value="PERMISOS_SECCION" <?php echo (in_array("PERMISOS_PREGUNTAS",$this->permisos))?"checked":""?>/>--></td>
						</tr>

						<tr>
							<td>Categorías</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_CATEGORIA" <?php echo (in_array("VER_CATEGORIA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_CATEGORIA" <?php echo (in_array("AGREGAR_CATEGORIA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_CATEGORIA" <?php echo (in_array("EDITAR_CATEGORIA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_CATEGORIA" <?php echo (in_array("ELIMINAR_CATEGORIA",$this->permisos))?"checked":""?>/></td>
							<!--<td align="center"></td>-->
							<td align="center"><!--<input type="checkbox" name="permisos[]" value="PERMISOS_SECCION" <?php echo (in_array("PERMISOS_PREGUNTAS",$this->permisos))?"checked":""?>/>--></td>
						</tr>
				
						<tr>
							<td>Encuestas</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_ENCUESTAS" <?php echo (in_array("VER_ENCUESTAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_ENCUESTAS" <?php echo (in_array("AGREGAR_ENCUESTAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_ENCUESTAS" <?php echo (in_array("EDITAR_ENCUESTAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_ENCUESTAS" <?php echo (in_array("ELIMINAR_ENCUESTAS",$this->permisos))?"checked":""?>/></td>
							<!--<td align="center"></td>-->
							<td align="center"><!--<input type="checkbox" name="permisos[]" value="PERMISOS_ENCUESTAS" <?php echo (in_array("PERMISOS_ENCUESTAS",$this->permisos))?"checked":""?>/>--></td>
						</tr>
						<tr>
							<td>Empresas</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_EMPRESA" <?php echo (in_array("VER_EMPRESA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_EMPRESA" <?php echo (in_array("AGREGAR_EMPRESA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_EMPRESA" <?php echo (in_array("EDITAR_EMPRESA",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_EMPRESA" <?php echo (in_array("ELIMINAR_EMPRESA",$this->permisos))?"checked":""?> /></td>
							<td align="center"></td>
						</tr>
						<tr>
							<td>Zonas</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_ZONAS" <?php echo (in_array("VER_ZONAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_ZONAS" <?php echo (in_array("AGREGAR_ZONAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_ZONAS" <?php echo (in_array("EDITAR_ZONAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_ZONAS" <?php echo (in_array("ELIMINAR_ZONAS",$this->permisos))?"checked":""?> /></td>
							<td align="center"></td>
						</tr>
						<tr>
							<td>Pre-registros</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_PRE_REGISTRO" <?php echo (in_array("VER_PRE_REGISTRO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="AGREGAR_PRE_REGISTRO" <?php echo (in_array("AGREGAR_PRE_REGISTRO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="EDITAR_PRE_REGISTRO" <?php echo (in_array("EDITAR_PRE_REGISTRO",$this->permisos))?"checked":""?> /></td>
							<td align="center"><input type="checkbox" name="permisos[]" value="ELIMINAR_PRE_REGISTRO" <?php echo (in_array("ELIMINAR_PRE_REGISTRO",$this->permisos))?"checked":""?> /></td>
							<td align="center"></td>
						</tr>
						<tr>
							<td>Asignaci&oacute;n de encuesta</td>
							<td align="center"><input type="checkbox" name="permisos[]" value="VER_ASIGNA_ENCUESTA" <?php echo (in_array("VER_ASIGNA_ENCUESTA",$this->permisos))?"checked":""?> /></td>
							<td align="center">&nbsp;</td>
							<td align="center">&nbsp;</td>
							<!--<td align="center">&nbsp;</td>-->
							<td align="center">&nbsp;</td>
						</tr>
					</tbody>
				</table>
			
			</div>
		</div>
		
			
		
	</div>
	<input type="hidden" name="id" id="id" value="<?php echo $this->registro->id?>" />
	<div class="text-right"> 
	<button class="btn btn-rojo-1" onclick="guardarPermisos();" type="button" ><i class="fa fa-check-circle"></i> Aceptar</button>
	<button class="btn btn-rojo-1" onclick="cancelar();" type="button" ><i class="fa fa-times-circle"></i> Cancelar</button>
	</div>
	<br/><br/><br/>  
</form>