<script type="text/javascript">
	window.onload = function() {
  		cambiaTipoUsuario(this.value,1);
		};
</script>

<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
    Espere un momento, por favor...
    <div class="progress">
        <div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <span class="sr-only">100% Completo</span>
        </div>
    </div>
</div>


	<form id="frmEditarMsje" name="frmEditarMsje" class="form-horizontal" method="post" action="/backend/editarMensaje/guardar" role="form" >

	<div class="col-xs-12 form-group">


        <label for="tipo_usuario" class="col-xs-2 control-label"><span class="naranja">*</span>Tipo de Usuario:</label>
        <div class="col-xs-4">
            <select name="tipo_usuario" class="form-control required" id="tipo_usuario" onchange="cambiaTipoUsuario(this.value,<?php echo $this->zona[0]->id; ?>);">
                
                <?php foreach ($this->tipos_usuarios as $tipo_usuario): ?>

	                    <option value="<?php echo $tipo_usuario->id ?>" <?php echo (($this->registro[0]->tipo_usuario_id == $tipo_usuario->id)?'selected':'') ?>><?php echo utf8_encode($tipo_usuario->descripcion) ?></option>

	                <?php endforeach ?>
                <option value="0">Todos</option>
            </select>
        </div>


	        <label for="fecha_limite" class="col-xs-2 control-label"><span class="naranja">*</span>Fecha limite</label>
	        <div class="col-xs-4">
	        	<input type="text" name="fecha_limite" id="fecha_limite" class="form-control input-sm required" value="<?php echo date_format($this->registro[0]->duedate_at,'Y-m-d') ?>" placeholder="Fecha limite">    
	        </div>            
	          
	</div>

	<div class="col-xs-12 form-group">
		<label for="usuario_destino" class="col-xs-2 control-label"><span class="naranja">*</span>Enviar a:</label>
				<div class="col-xs-4">
							
							<select id="usuario_destino" name="usuario_destino" class="form-control required" >
									<option value="" selected>-- Seleccione usuario --</option>
		
		 
			                <?php if (is_object($this->usu)): ?>
			                    <option value="<?php echo $this->usu->id; ?>">

			                    <?php echo $this->usu->usuario; ?></option>	              

			                <?php endif; ?>
			                <option value="<?php echo $this->registro[0]->usuario; ?>" selected><?php echo $this->registro[0]->usuario; ?></option>
		                    
							</select>
				</div>
				<label for="asunto" class="col-xs-2 control-label"><span class="naranja">*</span>Asunto:</label>
				<div class="col-xs-4">							
					<input type="text" id="asunto" name="asunto" class="form-control input-sm required" value="<?php echo $this->registro[0]->asunto; ?>" maxlength="250" placeholder="Asunto" />
				</div>

	</div>


		<div class="col-xs-12 form-group">

	        <label for="status" class="col-xs-2 control-label"><span class="naranja"></span>Estatus:</label>
	        <div class="col-xs-4">
	                <select id="status" name="status" class="form-control input-sm">
	                    <option value="1" selected>Habilitado</option>
	                    <option value="0" >Deshabilitado</option>
	                </select>
	        </div>
        </div>



		    <br><br>
		    <div class="form-group">
		      <label for="mensaje"><span class="naranja">*</span>Mensaje:</label>
		      <textarea class="form-control" rows="5" id="mensaje" name="mensaje" placeholder="Escriba su mensaje aqui..."><?php echo $this->registro[0]->mensaje; ?></textarea>
		    </div>
		    <p><span class="naranja">*</span>Maximo 255 caracteres</p>
	</div>
    
    <div class="col-xs-12 text-right">

    <input type="hidden" name="mensaje_id" id="mensaje_id" value="<?php echo $this->registro[0]->id; ?>" /> <!-- cuando no es nuevo -->
    <button class="btn btn-rojo-1" onclick="guardar('frmEditarMsje','frmFiltrosEditarMensaje','/backend/editarMensaje/grid','/backend/editarMensaje/imprimir','/editarMensaje/exportar');" type="button" ><i class="fa fa-check-circle"></i> Enviar</button>
    <button class="btn btn-rojo-1" onclick="cancelar();" type="button" ><i class="fa fa-times-circle"></i> Cancelar</button>
    </div>

    </form>
         
	
    </div>
<div id="flexigrid"></div>
<div class="height-5"></div>