<div id="es-1" name="es-1" class="alert alert-success hide" style="padding-bottom: 0;" role="alert">
    Espere un momento, por favor...
    <div class="progress">
        <div class="progress-bar progress-bar-success progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <span class="sr-only">100% Completo</span>
        </div>
    </div>
</div>

    <form id="frmEncuesta" name="frmEncuesta" class="form-horizontal" method="post" action="/backend/encuestas/guardar" role="form" enctype="multipart/form-data">    
    <br/>  

    <div class="col-xs-12 form-group"> 
        <label for="nombre" class="col-xs-2 control-label"><span class="naranja">*</span>Nombre:</label>
        <div class="col-xs-4">
            <input type="text" id="nombre" name="nombre" class="form-control input-sm required" value="<?php echo $this->registro->nombre ?>"  maxlength="100" placeholder="Nombre" />
        </div>
        <label for="fecha_inicio" class="col-xs-2 control-label"><span class="naranja">*</span>Categor&iacute;a:</label>
        <div class="col-xs-4">
        <select class="form-control input-sm required" name="categoria_id" >
            <option value="" selected>Seleccione una categoría</option>
            <?php foreach ($this->categorias as $categoria): ?>
                <option value="<?php echo $categoria->id; ?>" <?php echo(($this->registro->categoria_id==$categoria->id)?'selected':'') ?>><?php echo $categoria->nombre; ?></option>
            <?php endforeach ?>
        </select>
        </div>
    </div>
    <div class="col-xs-12 form-group">
        <label for="status" class="col-xs-2 control-label"><span class="naranja"></span>Estatus:</label>
        <div class="col-xs-4">
                <select id="status" name="status" class="form-control input-sm">
                    <option value="1" selected>Habilitado</option>
                    <option value="0" >Deshabilitado</option>
                </select>
        </div>
    </div>
    <br>    
    
    <div class="col-xs-12 text-right mb40px">
        <input type="hidden" name="id" id="id" value="<?php echo $this->registro->id; ?>" /> <!-- cuando no es nuevo -->
        <button class="btn btn-rojo-1" onclick="guardar('frmEncuesta','frmFiltrosEncuestas','/backend/encuestas/grid','/backend/encuestas/imprimir','/encuestas/exportar');" type="button" ><i class="fa fa-check-circle"></i> Aceptar</button>
        <button class="btn btn-rojo-1" onclick="cancelar();" type="button" ><i class="fa fa-times-circle"></i> Cancelar</button>
    </div>
     

</form>