<div class="panel panel-default" style="margin: 5px 0;">
    <div class="pnl-heading-rojo-1 clearfix">
        <h3 class="panel-title pull-left">Encuestas</h3>
        <button type="button" onclick="agregarEncuesta('/backend/encuestas/agregar', 0, 'frmEncuesta','Registrar encuesta');" class="btn btn-sm btn-default pull-right <?php echo($this->puedeAgregar?"":"hide"); ?>">
            <i class="fa fa-plus"></i>&nbsp;Agregar
        </button>
    </div>
    <div class="panel-body">
        <form name="frmFiltrosEncuestas" id="frmFiltrosEncuestas">
            <div class="row margin-bottom-3">
                
                <div class="col-xs-3">
                    <label for="fnombre" class="sr-only">Nombre</label>
                    <input type="text" name="nombre" id="fnombre" class="form-control input-sm" value="" placeholder="Buscar categoría"/>
                </div>
                <div class="col-xs-3">
                <label for="fstatus" class="sr-only">Estatus</label>
                    <select id="fstatus" name="status" class="form-control input-sm">
                        <option value="">- Todos los estatus -</option>
                        <option value="1">Habilitado</option>
                        <option value="0">Deshabilitado</option>
                    </select>
                </div>
                <div class="col-xs-offset-3 col-xs-3 text-right">
                    <button class="btn btn-sm btn-default" type="button" onclick="filtrar('frmFiltroEncuestas','/backend/encuestas/grid','/backend/encuestas/imprimir','/backend/encuestas/exportar');">
                        <i class="fa fa-search"></i>&nbsp;Filtrar
                    </button>
                    <button class="btn btn-sm btn-default" type="button" onclick="limpiar('frmFiltrosencuestas','/backend/encuestas/grid');">
                        <i class="fa fa-eraser"></i>&nbsp;Limpiar
                    </button>
                </div>
    	    </div>
        </form>
    </div>
</div>
<div id="flexigrid"></div>
<div class="height-5"></div>